Add IBM granite template
ggml-org/llama.cpp pull request #10013
Opened 2024-10-23 11:29 UTC by arch-btw

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

Hi @ggerganov and @ngxson,

I'd like to contribute the IBM granite template to llama.cpp. 

I've made my best effort but I'm new to this, so could you please be so kind to review? Maybe you can see if it's alright. 

I've followed the wiki instructions but feel free to make changes or provide feedback on how to improve.

The model is here: https://huggingface.co/ibm-granite/granite-3.0-8b-instruct

Here is the current output of llama-cli:

> main: chat template example:
<|start_of_role|>system<|end_of_role|>
You are a helpful assistant<|end_of_text|>
<|start_of_role|>user<|end_of_role|>
Hello<|end_of_text|>
<|start_of_role|>assistant<|end_of_role|>
Hi there<|end_of_text|>
<|start_of_role|>user<|end_of_role|>
How are you?<|end_of_text|>
<|start_of_role|>assistant<|end_of_role|>

--

![granite](https://github.com/user-attachments/assets/cee61ddb-91ac-4c2e-af61-d778a3167696)

2024-10-23 19:57 UTC, ngxson requested changes

2024-10-23 19:57 UTC, ngxson commented on src/llama.cpp
> +        ss << "<|start_of_role|>" << role << "<|end_of_role|>" << "\n"
```suggestion
        ss << "<|start_of_role|>" << role << "<|end_of_role|>\n"
```

2024-10-23 19:57 UTC, ngxson commented on tests/test-chat-template.cpp
> +        "<|start_of_role|>system<|end_of_role|>You are a helpful assistant<|end_of_text|>\n<|start_of_role|>user<|end_of_role|>Hello<|end_of_text|>\n<|start_of_role|>assistant<|end_of_role|>Hi there<
```suggestion
        "<|start_of_role|>system<|end_of_role|>You are a helpful assistant<|end_of_text|>\n<|start_of_role|>user<|end_of_role|>Hello<|end_of_text|>\n<|start_of_role|>assistant<|end_of_role|>Hi there<|end_of_text|>\n<|start_of_role|>user<|end_of_role|>Who are you<|end_of_text|>\n<|start_of_role|>assistant<|end_of_role|>   I am an assistant   <|end_of_text|>\n<|start_of_role|>user<|end_of_role|>Another question<|end_of_text|>\n<|start_of_role|>assistant<|end_of_role|>\n",
```

Probably missing a new line at the end - please double check on your side

2024-10-23 19:58 UTC, ngxson commented on tests/test-chat-template.cpp
> +        "<|start_of_role|>system<|end_of_role|>You are a helpful assistant<|end_of_text|>\n<|start_of_role|>user<|end_of_role|>Hello<|end_of_text|>\n<|start_of_role|>assistant<|end_of_role|>Hi there<
You can also run chat template test locally:

```
make tests/test-chat-template && ./tests/test-chat-template
```

2024-10-26 12:25 UTC, arch-btw commented
@ngxson thank you so much for your help, I appreciate your time and effort!

I have applied your review 👍 

I have a quick question, when I run ```test-chat-template``` is it normal that it looks like this (screenshot below).
The part that confuses me is that <end_of_sentence> is not escaped but the other tags are.
And then user/assistant are on the same line, twice.

I'm not sure what it should look like in the context of this script, considering the other prompts have things like additional spacing as well.

![test-chat-template](https://github.com/user-attachments/assets/ec5cb1d2-78e3-42d7-9211-640a0b8b7cff)

2024-10-26 12:49 UTC, ngxson commented
You need to add an example up unformatted chat template in `test-chat-template`. Please look carefully in the file.

2024-10-27 01:21 UTC, arch-btw commented
Hi @ngxson 

Thank you again for your guidance!
I finally managed to get it to work! 😅 

Here is the output of ``make tests/test-chat-template && ./tests/test-chat-template``:

-----

![outputgranite](https://github.com/user-attachments/assets/63d50f0e-a1ea-4caa-9681-f2df40774053)

-----

And here is the output of ``./llama-cli -m granite-3.0-8B-instruct-F32-Q5_K_M.gguf -t 4 -p 'You are granite, an AI model.' --conversation --color --chat-template granite``:

![outputgranite2](https://github.com/user-attachments/assets/fcaa7eb1-c613-4a23-b28c-831b579097ec)

And a prompt example:

![outputgranite3](https://github.com/user-attachments/assets/c01205a4-1df8-42f8-a6ca-46f94314b58b)

2024-10-28 10:06 UTC, ngxson reviewed
Looks perfect now. Thanks

2024-10-28 10:06 UTC, ngxson commented on src/llama.cpp
> +} else {
small nits before I can merge: the indentation here is incorrect (missing one level)

2024-10-28 10:06 UTC, ngxson commented on src/llama.cpp
> +    for (const auto& message : chat) {
code style:

```suggestion
    for (const auto & message : chat) {
```

2024-10-28 11:33 UTC, arch-btw commented
@ngxson Thank you again and sorry about that!

2024-10-28 15:09 UTC, ngxson approved these changes
Thanks, merging once the CI passes

2024-10-28 15:09 UTC, ngxson commented on src/llama.cpp
> +            std::string role(message -> role);
```suggestion
            std::string role(message->role);
```

2024-10-28 15:09 UTC, ngxson commented on src/llama.cpp
> +               << message -> content << "<|end_of_text|>\n";
```suggestion
               << message->content << "<|end_of_text|>\n";
```

2024-10-28 15:09 UTC, ngxson commented on src/llama.cpp
> +        for (const auto & message: chat) {
```suggestion
        for (const auto & message : chat) {
```

2024-10-28 17:45 UTC, merged