ci: add Ascend CANN build
ggml-org/llama.cpp pull request #10217
Opened 2024-11-08 09:41 UTC by xuedinge233

2024-11-19 11:22 UTC, hipudding commented on .github/workflows/build.yml
> +            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DWITH_CANN=on
-DGGML_CANN=on

2024-11-19 11:22 UTC, hipudding commented on .github/workflows/build.yml
> +        cann: ['python3.9-cann8.0.rc2.beta1']
Use newer version.

2024-11-19 11:23 UTC, hipudding commented on .github/workflows/build.yml
> +  openEuler-latest-cmake-cann:
openEuler-latest-cmake-cann-build, add build to job name to show this is a build test.

2024-11-19 11:25 UTC, hipudding requested changes
Need use correct cmake command.

2024-11-21 03:37 UTC, hipudding commented on .github/workflows/build.yml
> +      image: ascendai/cann:openeuler-${{ matrix.cann }}
first openeuler, and then ubuntu

2025-01-20 01:22 UTC, hipudding commented
Please use x86 image for build test.

2025-01-20 01:26 UTC, shink commented on .github/workflows/build.yml
> +          cmake --build .
You can use the `linux/amd64` Docker image of Ascend CANN directly, here is an example:

```
jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: ascendai/cann:latest
    steps:
      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
              git gcc g++ make cmake ninja-build curl \
              libgl1 libglib2.0-0 libsndfile1

      # See: https://github.com/actions/checkout/issues/363#issuecomment-1915075699
      - name: Config git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4
```

2025-01-20 09:40 UTC, shink commented on .github/workflows/build.yml
> +          export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/x86_64-linux/devlib/:${LD_LIBRARY_PATH}
refer: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell

2025-01-21 01:45 UTC, shink commented on .github/workflows/build.yml
> +          export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/x86_64-linux/devlib/:${LD_LIBRARY_PATH}
Seems can not work

2025-01-21 06:20 UTC, shink approved these changes

2025-01-21 07:07 UTC, hipudding commented
I think it's better triggered by 'Ascend NPU' label, I don't want it block others' PR.

2025-01-21 07:45 UTC, shink commented on .github/workflows/build.yml
> +        image: ascendai/cann:${{ matrix.cann }}
Need to format

2025-01-22 02:08 UTC, shink commented on .github/workflows/build.yml
> +    if: contains(github.event.pull_request.labels.*.name, 'Ascend NPU')
```suggestion
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'Ascend NPU') }}
```

2025-01-22 02:09 UTC, shink commented on .github/workflows/build.yml
> +    if: contains(github.event.pull_request.labels.*.name, 'Ascend NPU')
Only check labels when triggered by a PR event

2025-01-24 08:36 UTC, hipudding approved these changes

2025-01-24 08:38 UTC, hipudding commented
@slaren Could you please review this PR? Thanks. This PR add build check for Ascend NPU, Only enable when "Ascend NPU" label set.

2025-01-24 23:24 UTC, slaren approved these changes

2025-01-24 23:26 UTC, merged