[fix] Modify the status of finish_reason if the stream value is False
ggml-org/llama.cpp pull request #10382
Opened 2024-11-18 11:35 UTC by SeongBeomLEE

"finish_reason" returns "stop" in all cases because the "stop_word" value is always "True" when using "stream false mode" in /chat/completions API.

So modify the "stopped_word" value so that "length" can also be returned.

Thanks.

2024-11-18 15:41 UTC, ngxson approved these changes
LGTM, thanks!

2024-11-18 20:28 UTC, ngxson requested changes
I temporary revoke my approval because the CI failed.

I think it's likely due to another bug in the code. In anyway, the 3 bool `stopped_eos`, `stopped_word`, `stopped_limit` are too hacky and they should be refactored into one single enum.

I would appreciate if you (or someone) can take time to refactor this whole `stopped_*` machanism.

2024-11-20 00:38 UTC, SeongBeomLEE commented
@ngxson 

can you merge the current PR to resolve the issue?

I will leave another PR later on what you talked about.

thanks.

2024-12-06 10:02 UTC, ngxson commented
I'm closing this because I moved `stopped_*` to an enum in https://github.com/ggerganov/llama.cpp/pull/10643

`finish_reason` should now be correct.

2024-12-06 10:02 UTC, closed without merging