fix: ld link test-tokenizer-0 error
ggml-org/llama.cpp pull request #1042
Opened 2023-04-18 16:14 UTC by fumiama

```
cmake3 --build . --config Release
[  5%] Built target ggml
[ 16%] Built target llama
[ 22%] Linking CXX executable ../bin/test-tokenizer-0
../libllama.a(ggml.c.o)：在函数‘ggml_graph_compute’中：
ggml.c:(.text+0xf2db)：对‘pthread_create’未定义的引用
ggml.c:(.text+0xf9d4)：对‘pthread_join’未定义的引用
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/test-tokenizer-0] 错误 1
gmake[1]: *** [tests/CMakeFiles/test-tokenizer-0.dir/all] 错误 2
gmake: *** [all] 错误 2
```

2023-04-18 16:34 UTC, Green-Sky requested changes
1. Don't link to pthread directly. Use cmake `Threads::Threads` package instead.
2. This should not be necessarily in the first place since the `ggml` target gets linked with `Threads::Threads` already.

It might be that https://github.com/ggerganov/llama.cpp/blob/42747220b4cac548b6e3059b66b3e960b517cfa4/CMakeLists.txt#L273-L279
ggml being an `OBJECT` library and the dependencies being private causes issues.
Can you test with making the `ggml` target `STATIC` instead and or making the dependencies `PUBLIC` instead?

2023-04-18 17:00 UTC, Green-Sky requested changes
change `PRIVATE` to `PUBLIC` instead of dropping it completely. fits more the style of the rest of the project and is generally better code.

@ggerganov seems like `OBJECT` libraries having private dependencies does not make sense, since they don't have a linking step. Or it just breaks with certain cmake versions?

2023-04-18 17:10 UTC, fumiama commented
> change `PRIVATE` to `PUBLIC` instead of dropping it completely. fits more the style of the rest of the project and is generally better code.

Thanks. I don't know much about cmake.

2023-04-18 17:21 UTC, Green-Sky approved these changes

2023-04-21 18:26 UTC, ggerganov approved these changes

2023-04-21 18:27 UTC, merged