fix: ggml: fix vulkan-shaders-gen build
ggml-org/llama.cpp pull request #10448
Opened 2024-11-22 02:42 UTC by sparkleholic

The vulkan-shaders-gen target was not being built correctly in case of cross-compilation.
Other outputs need to be built for the cross compile target, but vulkan-shaders-gen needs to be built for the host.

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

2024-11-25 16:12 UTC, sparkleholic commented
@jeffbolznv , @0cc4m 
This fix is ​​needed for cross-compilation.
`vulkan-shaders-gen` is needed at build time, so `arch` should be the same as `host pc`, but other binaries (libggml, libllama, etc.) are needed at runtime.
Therefore, CMAKE compilation variables that apply when building the llama.cpp project should not apply when building vulkan-shaders-gen.

2024-11-25 16:52 UTC, 0cc4m commented
@sparkleholic @jeffbolznv I understand, I'm sorry that a few PRs are getting delayed because of me. I'm currently ill, but getting better and I should be able to catch up with all of them later this week.

Maybe you can resolve the merge conflict already?

2024-11-25 17:52 UTC, jeffbolznv commented
No rush, get well!

I'm not an expert at cmake or cross compilation, so I don't think I should review the change.

2024-11-25 18:52 UTC, sparkleholic commented
@0cc4m 
master rebased to resolve conflicts.
I didn't mean to rush you. I sincerely hope you feel better soon. :)

2024-11-27 06:26 UTC, 0cc4m commented
I can confirm this still works as usual on my system, but I'm also not a CMake expert. Maybe @bandoti can take a look?

2024-11-27 14:27 UTC, bandoti commented
I am happy to take a look. The one thing that comes to mind here after initial look through is being able to customize the compiler in this case. In particular, `gcc` and `g++` are hardcoded.

It would be worthwhile to add a default toolchain file for the build and allow one to customize by passing `-DGGML_SHADERS_GEN_CROSS_TOOLCHAIN=...` (or similar)

This would allow one to use a desire toolchain—maybe clang, etc.

2024-11-28 03:42 UTC, sparkleholic commented
@bandoti 
Thank you for the valuable feedback.

I have updated the code to handle the `GGML_SHADERS_GEN_TOOLCHAIN` variable. When this variable is provided, the specified file is used. If it is not set, the code generates a temporary host toolchain file by detecting the host environment's compiler.

Please review the updated code once again.

2024-12-02 12:30 UTC, 0cc4m commented
@bandoti Can you take another look?

2024-12-02 15:15 UTC, bandoti requested changes

2024-12-02 15:16 UTC, bandoti commented
@sparkleholic Sorry for the delay! I had these review comments in but forgot to submit them. 🤦‍♂️

2024-12-15 23:58 UTC, bandoti commented
@sparkleholic Just following up on this change. If you need further assistance please let me know I am happy to help.

2024-12-24 03:27 UTC, sparkleholic commented
@bandoti < Sorry for the late reply.
Thank you for the comments. I'll follow up this in coming 2~3 days.

2024-12-24 03:49 UTC, sparkleholic commented on ggml/src/ggml-vulkan/CMakeLists.txt
> +    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
addressed.

2024-12-24 03:49 UTC, sparkleholic commented on ggml/src/ggml-vulkan/CMakeLists.txt
> +            file(WRITE ${CMAKE_BINARY_DIR}/host_toolchain.cmake
addressed.

2024-12-24 04:03 UTC, sparkleholic commented
Rebased branch to latest master.

2024-12-28 20:07 UTC, bandoti commented
@sparkleholic No worries on the delay! Your contribution is greatly appreciated :)

It appears as though the test failure is unrelated to this. I'm wondering if merging the latest and rerunning the tests will clear the status. I have only one minor question in the review.

2024-12-28 20:09 UTC, bandoti commented on ggml/src/ggml-vulkan/vulkan-shaders/CMakeLists.txt
> +if (${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
Is the intention here to be the variable value or the name?
```
if (CMAKE_RUNTIME_OUTPUT_DIRECTORY)
```

2025-01-08 14:03 UTC, bandoti commented
@sparkleholic I have submitted a pull request to your master_fix branch which updates to latest and resolves a minor merge conflict. Please merge it into your branch so we can get the CI fixed here and merge these changes in!

Here's the PR for reference: https://github.com/sparkleholic/llama.cpp/pull/2

2025-01-09 05:19 UTC, sparkleholic commented
> @sparkleholic I have submitted a pull request to your master_fix branch which updates to latest and resolves a minor merge conflict. Please merge it into your branch so we can get the CI fixed here and merge these changes in!
> 
> Here's the PR for reference: [sparkleholic#2](https://github.com/sparkleholic/llama.cpp/pull/2)

@bandoti < Thanks a lot!
I'l like to merge your PR into my branch first to proceed this PR.
![image](https://github.com/user-attachments/assets/0cfcb94e-01fd-4605-8998-d93920060215)
Could you confirm which option should be selected for this?

2025-01-09 12:53 UTC, bandoti commented
@sparkleholic A regular merge commit (the default) should be good. Our changes here will get squashed once they merge it into master. 😊

2025-01-10 07:24 UTC, 0cc4m commented
You seem to have gathered a lot of unrelated changes here, the PR needs to be rebased before it can be merged.

2025-01-11 20:51 UTC, bandoti commented on ggml/src/ggml-vulkan/CMakeLists.txt
> +        find_program(GNU_C_COMPILER gcc)
I think we probably want `NO_CMAKE_FIND_ROOT_PATH` for these `find_program` calls to ensure that when the cross-compile search path is rooted somewhere else, this will ensure that the proper location is searched.

2025-01-12 02:11 UTC, sparkleholic commented on ggml/src/ggml-vulkan/CMakeLists.txt
> +        find_program(GNU_C_COMPILER gcc)
@bandoti < It's good point.
Yes, `NO_CMAKE_FIND_ROOT_PATH` seems to be required here.
I'll address it.

2025-01-12 02:55 UTC, sparkleholic commented on ggml/src/ggml-vulkan/vulkan-shaders/CMakeLists.txt
> +if (${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
Removed unnecessary code.

2025-01-12 14:28 UTC, bandoti requested changes
Everything seems good to me except my one comment on `detect_host_compiler`. After that (whether the suggestion works or not and we keep it as-is) I am happy to move forward!

2025-01-13 01:56 UTC, sparkleholic commented on ggml/src/ggml-vulkan/CMakeLists.txt
> +function(detect_host_compiler)
Your suggested code looks much more concise and better. However, on Windows where MSVC_COMPILER exists, it seems like it would be better to search for cl with the highest priority. To do this, I modified the compiler listing order of find_program to put cl first instead of searching for MSVC_COMPILER.

2025-01-13 02:21 UTC, sparkleholic commented on ggml/src/ggml-vulkan/CMakeLists.txt
> +function(detect_host_compiler)
@bandoti <
On Windows, I think the MSVC compiler would be the most stable one to look for, but I'm not sure if it's necessary. Would you please give me your opinion on which of the options below would be better.

* option1
     * Searching order: gcc clang cl in all platforms.
     * In this case, we can remove detect_host_compiler function, could write only two lines in the location calling that function.
```
function(detect_host_compiler)
    find_program(HOST_C_COMPILER NAMES gcc clang cl NO_CMAKE_FIND_ROOT_PATH)
    find_program(HOST_CXX_COMPILER NAMES g++ clang++ cl NO_CMAKE_FIND_ROOT_PATH)
endfunction()
```
* option2
     * Searching order: cl gcc clang in all platforms.
However, there is a downside to assuming an unnecessary process of finding cl even on non-Windows platforms.
     * In this case, we can remove detect_host_compiler function, could write only two lines in the location calling that function.
```
function(detect_host_compiler)
    find_program(HOST_C_COMPILER NAMES cl gcc clang NO_CMAKE_FIND_ROOT_PATH)
    find_program(HOST_CXX_COMPILER NAMES cl g++ clang++ NO_CMAKE_FIND_ROOT_PATH)
endfunction()
```
* option3
For Windows only, the cl compiler is found and applied with the highest priority.
```
function(detect_host_compiler)
    if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
        find_program(MSVC_COMPILER cl NO_CMAKE_FIND_ROOT_PATH)
        if (MSVC_COMPILER)
            set(HOST_C_COMPILER "${MSVC_COMPILER}" PARENT_SCOPE)
            set(HOST_CXX_COMPILER "${MSVC_COMPILER}" PARENT_SCOPE)
            return()
        endif()
    endif()
    find_program(HOST_C_COMPILER NAMES gcc clang NO_CMAKE_FIND_ROOT_PATH)
    find_program(HOST_CXX_COMPILER NAMES g++ clang++ NO_CMAKE_FIND_ROOT_PATH)
endfunction()
```

2025-01-13 05:49 UTC, sparkleholic commented
Please hold off on merging this patch for a moment. I'm checking my cross-compilation environment one last time.

2025-01-13 07:19 UTC, sparkleholic commented
FYI: @jeffbolznv 
Added a necessary change for cross-compiling environment.
https://github.com/ggerganov/llama.cpp/pull/10448/commits/37d0cb6e848ac4c96066f41c3e8ac2e629bd8ba9

2025-01-13 07:20 UTC, sparkleholic commented
@bandoti <
Ready to merge.

2025-01-13 13:03 UTC, bandoti requested changes

2025-01-13 13:03 UTC, bandoti commented on ggml/src/ggml-vulkan/vulkan-shaders/CMakeLists.txt
> +find_program(GLSLC_EXECUTABLE glslc)
We probably need the `NO_CMAKE_FIND_ROOT_PATH` option here as well.

2025-01-13 14:41 UTC, sparkleholic commented on ggml/src/ggml-vulkan/vulkan-shaders/CMakeLists.txt
> +find_program(GLSLC_EXECUTABLE glslc)
I think this line can be used with CMAKE_FIND_ROOT_PATH, depending on the user's intention. For example, the user could set their own CMAKE_TOOLCHAIN_FILE using the GGML_SHADERS_GEN_TOOLCHAIN variable instead of using ggml/src/ggml-vulkan/host_toolchain.cmake.in, and define CMAKE_FIND_ROOT_PATH to specify a path specific to the host system.

2025-01-13 14:52 UTC, bandoti commented on ggml/src/ggml-vulkan/vulkan-shaders/CMakeLists.txt
> +find_program(GLSLC_EXECUTABLE glslc)
That's fair. Okay, we can follow up with new PR if this causes an issue. :)

2025-01-13 14:52 UTC, bandoti approved these changes
Looks good to me!

2025-01-14 09:37 UTC, sparkleholic commented
@bandoti 
This PR is still opened.

2025-01-14 09:41 UTC, 0cc4m commented
> @bandoti , @ngxson This PR is still open...

It needs approval from a contributor. I'll do a quick test that everything runs as intended on a regular setup later today and merge if it's fine.

2025-01-14 09:43 UTC, ngxson commented
This change is not related to my part. I was added because you pushed a merge commit or rebase.

Please ask for people who maintains the vulkan backend.

2025-01-14 09:53 UTC, ggerganov commented on ggml/src/ggml-vulkan/host_toolchain.cmake.in
This file should be moved to a `cmake` subfolder and use dash instead of underscore: `ggml/src/ggml-vulkan/cmake/host-toolchain.cmake.in`

2025-01-15 08:44 UTC, ggerganov commented on ggml/CMakeLists.txt
> +set   (GGML_SHADERS_GEN_TOOLCHAIN "" CACHE FILEPATH "ggml: toolchain file for vulkan-shaders-gen")
This option should have a `GGML_VULKAN` prefix. For example, it can be named `GGML_VULKAN_SHADERS_GEN_TOOLCHAIN`

2025-01-15 09:21 UTC, 0cc4m commented on ggml/CMakeLists.txt
> +set   (GGML_SHADERS_GEN_TOOLCHAIN "" CACHE FILEPATH "ggml: toolchain file for vulkan-shaders-gen")
Do you have more comments or is that it? The PR has been open for way too long now and I'd like to get it merged.

2025-01-15 09:27 UTC, ggerganov approved these changes

2025-01-15 09:27 UTC, ggerganov commented on ggml/CMakeLists.txt
> +set   (GGML_SHADERS_GEN_TOOLCHAIN "" CACHE FILEPATH "ggml: toolchain file for vulkan-shaders-gen")
No, merge at will.

2025-01-15 10:19 UTC, sparkleholic commented on ggml/CMakeLists.txt
> +set   (GGML_SHADERS_GEN_TOOLCHAIN "" CACHE FILEPATH "ggml: toolchain file for vulkan-shaders-gen")
Addressed. Thanks.

2025-01-15 13:16 UTC, 0cc4m approved these changes
Thank you for your patience with all the feedback. I tested it and found no issues.

2025-01-15 13:17 UTC, merged