Changes to CMakePresets.json to add ninja clang target on windows
ggml-org/llama.cpp pull request #10668
Opened 2024-12-05 06:26 UTC by Srihari-mcw

This PR adds changes to CMakePresets.json to add a ninja clang target on windows. This will help users to build llama.cpp with clang and ninja dependencies, with relative ease. The additional dependencies are listed in build.md

Build commands : 

        cmake --preset x64-windows-ninja-release
        cmake --build build-x64-windows-ninja-release

Experiments were conducted to test llama.cpp with MSVC (Visual Studio Generator), Clang (Ninja) and Clang-Cl (Visual Studio Generator) and to compare the performance

Best performance was seen among the three for clang with ninja generator

**Ninja Generator, Clang.exe/Clang++.exe (17.0.3)**

- Clang.exe and clang++.exe are obtained from the same path as clang-cl - C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
- CMAKE Command : cmake -G "Ninja" -S . -B Windows-build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe
- Ninja path : C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe and version (1.11.0)
- Additional library depedencies are resolved with : set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\lib\x64\uwp;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64 before cmake and build

Both the clang builds are done without the openmp dependencies

The tests were conducted in AMD Raphael 7600X which supports the following flags (The same were kept on in our windows tests) : 
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | AVX512_BF16 = 1 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1|

**Prompt Processing** 

| model| Compiler/Generator| size| params | backend | threads | test | t/s | speedup | Commit id |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |------------- | ------------- | ------------- |
| llama 7B Q4_0 | MSVC Compiler/ VS Generator | 3.56 GiB | 6.74 B | CPU | 6 | pp 512 |  48.14  ±  0.67 | | [231f936](https://github.com/ggerganov/llama.cpp/commit/231f9360d94446cd083b6b116f63991b1328c484) |
| llama 7B Q4_0 | clang-cl.exe/ VS Generator | 3.56 GiB | 6.74 B | CPU | 6 | pp 512 |  50.23 ± 0.91 | 4.33% | [231f936](https://github.com/ggerganov/llama.cpp/commit/231f9360d94446cd083b6b116f63991b1328c484)  |
| llama 7B Q4_0 | clang.exe/ Ninja Generator  | 3.56 GiB | 6.74 B | CPU | 6 | pp 512 | 55.69 ± 0.71 | 15.68% | [231f936](https://github.com/ggerganov/llama.cpp/commit/231f9360d94446cd083b6b116f63991b1328c484) |

**Text Generation** 

| model| Compiler/Generator| size| params | backend | threads | test | t/s | speedup | Commit id |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |------------- | ------------- | ------------- |
| llama 7B Q4_0 | MSVC Compiler/ VS Generator | 3.56 GiB | 6.74 B | CPU | 6 | tg 128 |  14.8 ± 0.01 | | [231f936](https://github.com/ggerganov/llama.cpp/commit/231f9360d94446cd083b6b116f63991b1328c484) |
| llama 7B Q4_0 | clang-cl.exe/ VS Generator | 3.56 GiB | 6.74 B | CPU | 6 | tg 128 |  14.95 ± 0.02 | 1.00% | [231f936](https://github.com/ggerganov/llama.cpp/commit/231f9360d94446cd083b6b116f63991b1328c484)  |
| llama 7B Q4_0 | clang.exe/ Ninja Generator | 3.56 GiB | 6.74 B | CPU | 6 | tg 128 | 14.95 ± 0.02 | 1.00% | [231f936](https://github.com/ggerganov/llama.cpp/commit/231f9360d94446cd083b6b116f63991b1328c484) |

OS : Windows

Tests done with [Meta Llama2 7B model](https://huggingface.co/meta-llama/Llama-2-7b)

2024-12-05 18:28 UTC, max-krasnyansky commented
Do you want to maybe just match what I did for the Windows on ARM64 `arm64-windows-llvm` ?
i.e add CMake toolchain file that uses llvm/clang and call the targets x64-windows-llvm that use Ninja.
The main performance difference is llvm/clang not Ninja. 
We should just use Ninja as the default anyway. It's faster in general and cleaner output.

2024-12-06 14:02 UTC, Srihari-mcw commented
Hi @max-krasnyansky , the preset target names were changed as per the above comment. The aim is to facilitate users to build with clang on x64/x86 Platforms on windows. Thanks

2024-12-06 17:27 UTC, max-krasnyansky approved these changes

2024-12-06 17:35 UTC, max-krasnyansky requested changes
Sorry. I approved first but then realized that there is still no toolchain file. 
Just copy cmake/arm64-windows-llvm.cmake to cmake/x64-windows-llvm.cmake and update CFLAGS and things.
We probably don't need to use `.exe` in the compiler name either.

2024-12-09 15:11 UTC, Srihari-mcw commented
HI @max-krasnyansky ,

updates were made to use .cmake file. Thanks

2024-12-09 17:39 UTC, max-krasnyansky approved these changes

2024-12-09 17:39 UTC, max-krasnyansky commented on docs/build.md
> +      cmake --preset x64-windows-ninja-release
```suggestion
      cmake --preset x64-windows-llvm-release
```

2024-12-09 17:39 UTC, max-krasnyansky commented on docs/build.md
> +      cmake --build build-x64-windows-ninja-release
```suggestion
      cmake --build build-x64-windows-llvm-release
```

2024-12-09 17:40 UTC, merged