Adding missing features of CMakeLists.txt & Refactoring
ggml-org/llama.cpp pull request #131
Opened 2023-03-14 12:57 UTC by nusu-github

We have come up with several changes to CMakeLists.txt that are expected to improve performance, compatibility, and maintainability, and we have drafted them.

Change list :
1. remove _NO_ from option names that have _NO_ in the option name.
Change LLAMA_NO_ACCELERATE to LLAMA_ACCELERATE to avoid "NOT NO" in if statements. 
2. make it possible to enable/disable SIMD extension instructions for non-Apple.
I see no reason to make it Apple-only. It should be possible to enable/disable on all platforms.
3. give priority to CMake functions.
Use "add_compile_options" instead of writing directly to CMAKE_C_FLAGS to avoid double flags and compile errors due to typos.
4. Add new options.
LLAMA_STATIC_LINK, LLAMA_NATIVE, and LLAMA_LTO were added.
LLAMA_STATIC_LINK is an option to enable static linking. This will be useful when compiling for Windows with MinGW and for future distribution.
Also, LLAMA_NATIVE to add -march=native and LLAMA_LTO for link-time optimization will both be useful options for this project for speed.
5. other changes.
cmake_minimum_required was changed to 3.9 for LTO support.
CMAKE_CXX_STANDARD was changed to c++11, the same as in the Makefile.
I made utils build using add_library and link to it.
Added Threads link since it was missing.
Added option LLAMA_OPENBLAS.  (Not tested).

We have confirmed that it works on MSVC, MSVC Clang GUN like (not clang-cl), MinGW, and Cygwin on Windows, but have not confirmed that it works on other platforms.
Also, prioritizing CMake's features may sometimes sacrifice simplicity.

P.S. Sorry if there is any strange English. This is using automatic translation.

2023-03-19 18:15 UTC, ggerganov approved these changes

2023-03-19 18:17 UTC, ggerganov commented
Someone figure out with the Windows build is failing and merge

2023-03-20 07:55 UTC, nusu-github commented
LLAMA_LTO was changed so that it can be used outside of Release so that it can be built on Windows.

2023-03-20 14:18 UTC, Green-Sky requested changes

2023-03-20 14:18 UTC, Green-Sky commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
I am not a fan of setting this globally. this should be specified for each target.
`target_compile_features(llama PUBLIC cxx_std_17)` or similar. same for c.

always consider what happens when the project is included via `add_subdirectoy()`

2023-03-20 15:13 UTC, Green-Sky reviewed
@ggerganov should we upgrade form cmake 3.9 to 3.12 ?

2023-03-20 15:17 UTC, nusu-github commented on CMakeLists.txt
> +add_library(ggml OBJECT
I don't think there is a problem, as it is described in the v3.9 documentation.
https://cmake.org/cmake/help/v3.9/command/add_library.html#object-libraries

2023-03-21 00:12 UTC, Green-Sky commented on CMakeLists.txt
> +add_library(ggml OBJECT
your cmake is >= 3.12 :)

the `cmake_minimum_required(VERSION 3.9)` at the top only checks if you have at least 3.9 , it does not say that you cant use newer feature.

2023-03-21 00:35 UTC, Green-Sky approved these changes

2023-03-21 00:37 UTC, merged

2023-03-21 02:38 UTC, anzz1 commented
What is the reasoning for changing C++11 standard to C++17 since the project does not use any of C++17 extensions? To my knowledge all compiler versions which support C++17 also support C++11, but not vice-versa.

2023-03-21 03:23 UTC, Green-Sky commented
@anzz1 we have been using c++17 features (string_view) since https://github.com/ggerganov/llama.cpp/commit/074bea2eb1f1349a0118239c4152914aecaa1be4

2023-03-21 06:55 UTC, nusu-github commented on CMakeLists.txt
> +add_library(ggml OBJECT
I always thought it was limited because there were some features that became unavailable when the version was lowered. Thank you for letting us know.

2023-03-21 10:20 UTC, Green-Sky commented on CMakeLists.txt
> +add_library(ggml OBJECT
it does to an extend. it affects policies.