Use F16 for memory_k and memory_v (as suggested in #146)
ggml-org/llama.cpp pull request #154
Opened 2023-03-15 06:16 UTC by ty-everett

As suggested in #146 we are able to save lots of memory by using float16 instead of float32. I implemented the suggested changes, and tested with the 7B and 13B models, and there were no issues on my Intel-based MacBook Pro.

Merging these changes should allow more models to run more performantly on a wider range of hardware.

2023-03-15 14:15 UTC, Green-Sky commented
can confirm `ggml ctx size` 4529.34 MB -> 4273.34 MB
speed stayed the same.

it is hard to tell if the quality changes, but the prediction does (obviously).

2023-03-15 19:14 UTC, ggerganov commented
I was worried that it might degrade quality, but I have no evals as you can guess.
I think it is best to gate this through a command line argument. Have it F32 by default, and if requested by the user - set it to F16

2023-03-15 19:14 UTC, ggerganov requested changes
.

2023-03-18 00:00 UTC, Green-Sky commented
@ty-everett  are you going to write the cli-param conditional version? if not, I will do it.

2023-03-19 18:18 UTC, closed without merging