Clblast fixes + enhancements to save VRAM and offload more layers
ggml-org/llama.cpp pull request #1675
Opened 2023-06-02 15:27 UTC by LostRuins

This PR builds on top of occam's changes, https://github.com/ggerganov/llama.cpp/pull/1653, which should be merged first.

Summary: This solves a problem where allocating and freeing gradually increasing sized device buffers in sequence ends up creating a lot of useless buffers that do not get fully utilized, squandering precious VRAM. For example, allocating and then freeing a `ggml_cl_pool_malloc` in the sequence 1gb->2gb->3gb->4gb ends up using a total of 10gb, whereas after this PR only 4gb would be utilized.

Clblast fixes + enhancements to save VRAM and offload more layers:

1. Change all Clblast buffers to `CL_MEM_READ_WRITE`, as the pool malloc currently doesn't properly handle them, since the original flags are not currently preserved.
2. When recycling buffers in pool malloc, always assign the SMALLEST available buffer that fits, instead of the FIRST available buffer.
3. When failing to recycle a buffer in pool malloc (if all existing free buffers are too small), instead recycle the largest available free buffer by resizing it.

With these enhancements I was able to load 2 additional GPU layers into VRAM, at no/minimal observed cost to performance.

This PR is built based off the `master` branch of llama.cpp and follows it's MIT license in full.

2023-06-02 16:47 UTC, YellowRoseCx commented
+1

2023-06-04 15:32 UTC, 0cc4m commented on ggml-opencl.cpp
> +    int best_i = -1, best_size = std::numeric_limits<size_t>::max(); //smallest unused buffer that fits our needs
I think this change is a good idea.

2023-06-04 15:32 UTC, 0cc4m commented on ggml-opencl.cpp
> +    int worst_i = -1, worst_size = 0; //largest unused buffer seen so far
This is less cluttered than the last one, but also looks better in two lines.

2023-06-04 15:32 UTC, 0cc4m commented on ggml-opencl.cpp
> +    cl_mem d_X = ggml_cl_pool_malloc(ne0 * sizeof(float), &x_size, CL_MEM_READ_WRITE); // src0
You could just remove the flags parameter of the malloc function in this case, we don't use it anymore.

2023-06-05 05:32 UTC, LostRuins commented
Fixes applied

2023-06-06 15:55 UTC, 0cc4m requested changes

2023-06-06 15:55 UTC, 0cc4m commented on ggml-opencl.cpp
> +         clReleaseMemObject(mem);
```suggestion
         clReleaseMemObject(mem);
```

2023-06-06 16:33 UTC, 0cc4m approved these changes

2023-06-06 17:00 UTC, merged