Use unsigned for random seed
ggml-org/llama.cpp pull request #2006
Opened 2023-06-26 15:00 UTC by howard0su

Based C++ document and POSIX document, random seed should be an unsigned integer. Change the code to reflect that.

In order to avoid break most the existing applications, let's use -1 as a special value to auto generate a time-based seed still.

Reported in #2002

2023-06-26 19:32 UTC, ggerganov requested changes

2023-06-26 19:32 UTC, ggerganov commented on llama.h
>          int n_gpu_layers;                      // number of layers to store in VRAM
Avoid `unsigned int`. Use `uint32_t` and `int32_t`

```suggestion
        uint32_t seed;                             // RNG seed, -1 for random
        int32_t  n_ctx;                            // text context
        int32_t  n_batch;                          // prompt processing batch size
        int32_t  n_gpu_layers;                     // number of layers to store in VRAM
```

2023-06-26 19:32 UTC, ggerganov commented on examples/embedding/embedding.cpp
> +    if (params.seed == -1) {
Wouldn't this cause compiler warnings?
I think better replace `-1` with `0xFFFFFFFF` everywhere, except in the help and the readme

2023-06-26 20:07 UTC, axim2 commented
Also gpt_params_parse() needs to be changed in examples/common.cpp on line 113: std::stoi => std::stoul

2023-06-28 15:51 UTC, ggerganov approved these changes
Merge after changing `unsigned int` -> `uint32_t`

2023-06-28 15:51 UTC, ggerganov commented on llama.cpp
> +void llama_set_rng_seed(struct llama_context * ctx, unsigned int seed) {
```suggestion
void llama_set_rng_seed(struct llama_context * ctx, uint32_t seed) {
```

2023-06-28 15:51 UTC, ggerganov commented on llama.h
> +    LLAMA_API void llama_set_rng_seed(struct llama_context * ctx, unsigned int seed);
```suggestion
    LLAMA_API void llama_set_rng_seed(struct llama_context * ctx, uint32_t seed);
```

2023-06-29 13:15 UTC, merged