Convert checks in llama_load_session_file to throw and handle them
ggml-org/llama.cpp pull request #2022
Opened 2023-06-27 14:32 UTC by randxie

This pull request addresses https://github.com/ggerganov/llama.cpp/issues/1716

Similar to `llama_model_load`, there is a `llama_model_load_internal` that throws exceptions for invalid cases, and the API `llama_model_load` handles the exceptions.

2023-06-27 15:40 UTC, howard0su approved these changes
LGTM, please fix the comment.

2023-06-27 16:40 UTC, randxie commented on llama.cpp
> +void llama_load_session_file_internal(struct llama_context * ctx, const char * path_session, llama_token * tokens_out, size_t n_token_capacity, size_t * n_token_count_out) {
Good catch!

2023-06-28 17:15 UTC, ggerganov requested changes
Avoid exceptions - bad practice

`llama_load_session_file()` has to return `bool`

2023-06-28 23:53 UTC, randxie commented
@ggerganov updated the pull request to avoid using exceptions. We still need the `llama_load_session_file_internal` because `file.read_raw` can raise exceptions.

Do we have plan to turn off all exceptions and probably adopt ideas like google::Status class? Otherwise reviewers have to keep checking if exceptions are being used in every pull request.

2023-07-01 15:58 UTC, ggerganov approved these changes

2023-07-01 15:59 UTC, ggerganov commented
Don't have experience with turning off exceptions all together.
If there is a way to do that without bloating things - we can consider it

2023-07-01 16:02 UTC, merged