ggml : mul mat tweaks
ggml-org/llama.cpp pull request #2372
Opened 2023-07-24 12:44 UTC by ggerganov

WIP in progress

See if #2355 can be resolved and also make sure we broadcast correctly across dims 2 and 3

2023-07-24 13:43 UTC, ggerganov commented
@coadmonky 

Can you check if this branch makes any performance difference on your system?

2023-07-24 18:25 UTC, yukiteruamano commented
Hi, I follow this issues too and these are the results in my case:

master branch

```
llama_print_timings:        load time =  1227,29 ms
llama_print_timings:      sample time =    83,16 ms /   136 runs   (    0,61 ms per token,  1635,36 tokens per second)
llama_print_timings: prompt eval time = 11299,55 ms /    53 tokens (  213,20 ms per token,     4,69 tokens per second)
llama_print_timings:        eval time = 30410,48 ms /   136 runs   (  223,61 ms per token,     4,47 tokens per second)
llama_print_timings:       total time = 162198,49 ms
```

mul-mat-tweaks branch

```
llama_print_timings:        load time =  1230,44 ms
llama_print_timings:      sample time =   141,66 ms /   250 runs   (    0,57 ms per token,  1764,84 tokens per second)
llama_print_timings: prompt eval time =  9965,68 ms /    53 tokens (  188,03 ms per token,     5,32 tokens per second)
llama_print_timings:        eval time = 56549,68 ms /   250 runs   (  226,20 ms per token,     4,42 tokens per second)
llama_print_timings:       total time = 128116,71 ms
```

The values are consistents into multiple runs

2023-07-25 10:17 UTC, ggerganov commented
@coadmonky 

I believe that the latest commit in this branch [2076a9b](https://github.com/ggerganov/llama.cpp/pull/2372/commits/2076a9b3d998331ec6948daf328aebb5a9dd6e1c) should restore the old performance. Please let me know if you get the chance to give it a try

2023-07-25 12:34 UTC, goerch requested changes

2023-07-25 12:34 UTC, goerch commented on ggml.c
> +                    vec_dot(ne00, &tmp[ir0 - iir0], src0_row + ir0*nb01, src1_col);
As far as I know `vec_dot` is cache unfriendly for `gemm`. IIRC you need a different loop order to reach high FLOPs.

2023-07-25 21:53 UTC, goerch commented on ggml.c
> +                    vec_dot(ne00, &tmp[ir0 - iir0], src0_row + ir0*nb01, src1_col);
[Here](https://gist.github.com/goerch/a14a582fb31182d962dbfc191baec097) is the best I came up for now without trying to rebuild `OpenBLAS`.

2023-08-07 11:25 UTC, merged

2023-08-07 11:26 UTC, ggerganov commented
Will complete the TODOs later in separate PRs