Allow passing grammar to completion endpoint
ggml-org/llama.cpp pull request #2532
Opened 2023-08-06 10:46 UTC by krasserm

## Description

This PR extend `server.cpp` to support submitting a grammar with `completion` requests (equivalent to the `--grammar` command line option for `main.cpp`)

## Usage example 

Start a server with a [Llama-2-13B-GGML](https://huggingface.co/TheBloke/Llama-2-13B-GGML/tree/main) model: 

```bash
./server -m llama-2-13b.ggmlv3.q4_0.bin -eps 1e-5 --n-gpu-layers 43 --host 0.0.0.0 --port 8080
```

Define schema of two functions in `functions.json`:

```json
{
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "function": {"const": "create_event"},
                "arguments": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "date": {"type": "string"},
                        "time": {"type": "string"}
                    }
                }
            }
        },
        {
            "type": "object",
            "properties": {
                "function": {"const": "image_search"},
                "arguments": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"}
                    }
                }
            }
        }
    ]
}
```

A Python program that uses the served model for grammar-based sampling:  

```python
import importlib
import json

import requests

# import examples/json-schema-to-grammar.py
schema = importlib.import_module("examples.json-schema-to-grammar")

with open("functions.json", "r") as f:
    functions_schema = json.load(f)

# Convert functions schema to grammar
prop_order = {name: idx for idx, name in enumerate(["function", "arguments"])}
converter = schema.SchemaConverter(prop_order)
converter.visit(functions_schema, '')
grammar = converter.format_grammar()

prompts = [
    "Schedule a birthday party on Aug 14th 2023 at 8pm.",
    "Find an image of a dog."
]

for prompt in prompts:
    data_json = { "prompt": prompt, "temperature": 0.1, "n_predict": 512, "stream": False, "grammar": grammar }

    resp = requests.post(
        url="http://127.0.0.1:8080/completion",
        headers={"Content-Type": "application/json"},
        json=data_json,
    )

    result = json.loads(resp.json()["content"].strip().replace("\n", "\\n"))

    print(f"Prompt: {prompt}")
    print(f"Result: {result}\n")
```

When running, it produces the following output:

```
Prompt: Schedule a birthday party on Aug 14th 2023 at 8pm.
Result: {'function': 'create_event', 'arguments': {'date': '2023-08-14T20:00:00Z', 'time': '20:00', 'title': 'Birthday Party'}}

Prompt: Find an image of a dog.
Result: {'function': 'image_search', 'arguments': {'query': 'dog'}}
```

2023-08-07 06:27 UTC, SlyEcho requested changes

2023-08-07 06:27 UTC, SlyEcho commented on examples/server/server.cpp
> +                return;
Should respond with an error code instead of silently printing on the console.

2023-08-07 06:27 UTC, SlyEcho commented on examples/server/server.cpp
> +                        "%s: warning: EOS token is disabled, which will cause most grammars to fail\n", __func__);
Please use the server logging functions.

2023-08-07 09:51 UTC, krasserm commented
@SlyEcho thanks for reviewing my PR. I just added a second commit that should cover your review comments. I'm not a C++ programmer but still hope these changes make sense.  Any guidance how to further improve this PR, if necessary, is highly appreciated!

2023-08-08 05:39 UTC, sbruce01 commented
Having issues with this fork. I've pulled then built with cmake, downloaded the model with:
```sh
export MODEL=llama-2-13b.ggmlv3.q4_0.bin
if [ ! -f models/${MODEL} ]; then
    curl -L "https://huggingface.co/TheBloke/Llama-2-13B-GGML/resolve/main/${MODEL}" -o models/${MODEL}
fi
```
Spun up the server with the same arguments except I'm running on a CPU:
```
./server -m ./models/llama-2-13b.ggmlv3.q4_0.bin -eps 1e-5 -t 48 --host 0.0.0.0 --port 8080
```
Copied the ```functions.json``` and Python file per description. Upon running in Python I get an error parsing the response.
```
Traceback (most recent call last):
  File "/home/ubuntu/llama.cpp/grammar.py", line 34, in <module>
    result = json.loads(resp.json()["content"].strip().replace("\n", "\\n"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
And printing out the ```resp.json()``` prior to the assignment of ```result``` it appears the LLM is in a loop echoing the content
```
{'content': '\nSchedule a birthday party on Aug 15th 2023 at 8pm.\nSchedule a birthday party on Aug 16th 2023 at 8pm.\nSchedule a birthday party on Aug 17th 2023 at 8pm.\nSchedule a birthday party on Aug 18th 2023 at 8pm.\nSchedule a birthday party on Aug 19th 2023 at 8pm.\nSchedule a birthday party on Aug 20th 2023 at 8pm.\nSchedule a birthday party on Aug 21st 2023 at 8pm.\nSchedule a birthday party on Aug 22nd 2023 at 8pm.\nSchedule a birthday party on Aug 23rd 2023 at 8pm.\nSchedule a birthday party on Aug 24th 2023 at 8pm.\nSchedule a birthday party on Aug 25th 2023 at 8pm.\nSchedule a birthday party on Aug 26th 2023 at 8pm.\nSchedule a birthday party on Aug 27th 2023 at 8pm.\nSchedule a birthday party on Aug 28th 2023 at 8pm.\nSchedule a birthday party on Aug 29th 2023 at 8pm.\nSchedule a birthday party on Aug 30th 2023 at 8pm.\nSchedule a birthday party on Aug 31st 2023 at 8pm.', 'generation_settings': {'frequency_penalty': 0.0, 'ignore_eos': False, 'logit_bias': [], 'mirostat': 0, 'mirostat_eta': 0.10000000149011612, 'mirostat_tau': 5.0, 'model': './models/llama-2-13b.ggmlv3.q4_0.bin', 'n_ctx': 512, 'n_keep': 0, 'n_predict': 512, 'n_probs': 0, 'penalize_nl': True, 'presence_penalty': 0.0, 'repeat_last_n': 64, 'repeat_penalty': 1.100000023841858, 'seed': 4294967295, 'stop': [], 'stream': False, 'temp': 0.10000000149011612, 'tfs_z': 1.0, 'top_k': 40, 'top_p': 0.949999988079071, 'typical_p': 1.0}, 'model': './models/llama-2-13b.ggmlv3.q4_0.bin', 'prompt': ' Schedule a birthday party on Aug 14th 2023 at 8pm.', 'stop': True, 'stopped_eos': True, 'stopped_limit': False, 'stopped_word': False, 'stopping_word': '', 'timings': {'predicted_ms': 29778.918, 'predicted_n': 391, 'predicted_per_second': 13.130094249898535, 'predicted_per_token_ms': 76.16091560102302, 'prompt_ms': 1002.677, 'prompt_n': 391, 'prompt_per_second': 22.938593385506998, 'prompt_per_token_ms': 43.59465217391305}, 'tokens_cached': 414, 'tokens_evaluated': 23, 'tokens_predicted': 392, 'truncated': False}
```
Let me know if I'm missing something as unable to replicate the output you've supplied

2023-08-08 07:19 UTC, SlyEcho approved these changes

2023-08-08 07:19 UTC, SlyEcho commented
Looks good now.

2023-08-08 07:51 UTC, krasserm commented
Thanks again for reviewing @SlyEcho. I just fixed the reported trailing whitespace error in another commit. Sorry for the extra round, checks should now pass.

2023-08-08 12:22 UTC, tobi commented
Very nice

2023-08-08 13:29 UTC, merged

2023-08-09 13:36 UTC, krasserm commented
@razorback16 I just submitted #2566 which fixes the issue you reported.

2023-08-09 16:11 UTC, razorback16 commented
Thank you for the fix. It works now :)

On Wed, Aug 9, 2023 at 6:37 AM Martin Krasser ***@***.***>
wrote:

> @razorback16 <https://github.com/razorback16> I just submitted #2566
> <https://github.com/ggerganov/llama.cpp/pull/2566> which fixes the issue
> you reported.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ggerganov/llama.cpp/pull/2532#issuecomment-1671342763>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGYD7SPNKAPOTAFQCUO4NDXUOHAFANCNFSM6AAAAAA3F2THZ4>
> .
> You are receiving this because you were mentioned.
>