CUDA: use 1 thread if model is fully offloaded
ggml-org/llama.cpp pull request #2915
Opened 2023-08-30 20:05 UTC by JohannesGaessler

Currently when using the maximum possible number of GPU layers with CUDA there is no benefit from > 1 thread. In fact, using more than 1 thread is detrimental due to increased overhead. This PR changes the logic for the default number of threads in such a way that (unless the user manually overrides it) only a single thread is used if all layers are offloaded.

I also changed the logic for `llama-bench` to be the same as `main`: -1 is interpreted as the number of logical cores.

2023-09-01 01:35 UTC, KerfuffleV2 commented
Maybe update the help for `main` also?

    -t N, --threads N     number of threads to use during computation (default: 8)

It might be good to mention the ability to set it to `-1`, `-2` (in both places) and what that does.

2023-09-01 11:02 UTC, Ph0rk0z commented
Using 1 vs 15 for me does make it .2-.5 tokens faster.

2023-09-02 12:41 UTC, ggerganov requested changes
Better to implement this entirely in `llama_eval_internal`, similar to what has been done for BLAS:

https://github.com/ggerganov/llama.cpp/blob/8b56b4f2c396eae1f4417e5a859557fed989e0ee/llama.cpp#L2899-L2904

2023-09-02 12:41 UTC, ggerganov commented on common/common.cpp
> +#endif // GGML_USE_CUBLAS
This is an implementation detail that the user should not need to know and in the future we will fix this anyway

2023-09-15 13:07 UTC, alitariq4589 commented
Can one of the admins verify this patch?

2023-09-16 14:02 UTC, JohannesGaessler commented
I haven't forgotten about this, I've only prioritized other things because I think that this is not that high priority.

2023-09-18 16:16 UTC, JohannesGaessler commented
@ggerganov thank you for the hint with `llama_eval_internal`, the implementation was way simpler this way.

2023-09-18 16:34 UTC, slaren approved these changes

2023-09-21 08:43 UTC, ggerganov approved these changes

2023-09-21 08:43 UTC, merged