Add test coverage of the GGUFWriter class by adding several test cases.
ggml-org/llama.cpp pull request #3036
Opened 2023-09-05 23:23 UTC by mendax0110

**Description:**

This pull request aims to enhance the test coverage of the GGUFWriter class by adding several test cases. 

**Changes Made:**

The following test cases have been added:

1. `test_gguf_writer`: This test case creates an instance of GGUFWriter, adds metadata, architecture information, and a tensor, and then writes the data to a file. Finally, it verifies the existence of the generated file.

2. `test_ggml_quantization_type`: This test case checks the correctness of GGMLQuantizationType constants, ensuring they have the expected values.

3. `test_gguf_value_type`: Similar to the previous test case, this one checks the correctness of GGUFValueType constants.

**Rationale:**

By adding these test cases, we improve the reliability of the GGUFWriter class. 
With these tests in place, we can have more confidence in the correctness of the GGUF library.

**Additional Notes:**

- All tests have been designed to clean up after themselves using a temporary directory created with `tempfile.TemporaryDirectory()`.
- The tests include assertions to verify the expected outcomes, making them suitable for use in a continuous integration (CI) environment.

## Reviewers

Any feedback on the added test cases and their coverage is greatly appreciated.

2023-09-05 23:41 UTC, akawrykow commented on gguf-py/tests/test_gguf.py
> +    assert os.path.exists(os.path.join(temp_dir, "test.gguf"))
Should we also verify the contents of the file? You could either create this actual file as a  gguf with the expected contents and check it in then compare whatever file we write with the snapshot, or you could use a gguf reader and pull out all the keys and assert they have the right values. That will guard against inadvertent changes to the format etc

2023-09-06 00:07 UTC, Cebtenzzre commented on gguf-py/tests/test_gguf.py
> +    assert GGMLQuantizationType.Q4_0 == 2
This test case doesn't do anything useful.

2023-09-06 06:53 UTC, monatis requested changes

2023-09-06 06:53 UTC, monatis commented on gguf-py/tests/test_gguf.py
> +def test_gguf_value_type():
This test is also redundant. There's no need to write test cases for enums / constants.
A better test case would be to read the written GGUF file, but there's no reader class implemented in Python yet. So we can verify the checksum of the file instead.

2023-09-09 16:45 UTC, Cebtenzzre commented
@mendax0110 There's no need to push merges if there aren't any conflicts. Every time you merge master, I get a notification.

2023-09-09 16:47 UTC, mendax0110 commented
> @mendax0110 There's no need to push merges if there aren't any conflicts. Every time you merge master, I get a notification.

Sorry!

2023-09-15 13:07 UTC, alitariq4589 commented
Can one of the admins verify this patch?

2023-10-01 11:23 UTC, closed without merging