CI: FreeBSD fix + Ubuntu make latest
ggml-org/llama.cpp pull request #3258
Opened 2023-09-19 09:45 UTC by alonfaraj

- Try to resolve FreeBSD CI hangs https://github.com/ggerganov/llama.cpp/pull/3053#issuecomment-1724399258.
  As mentioned here https://github.com/cross-platform-actions/action/issues/61, seems like qemu + macOS should function better, I think it worth a try before setting a timeout.  
  @Green-Sky what do you think?

- Update Ubuntu make job to use latest instead of Ubuntu 20.04 and gcc-8

2023-09-19 09:51 UTC, Green-Sky requested changes
> Update Ubuntu make job to use latest instead of Ubuntu 20.04 and gcc-8

this is actually intentional, to test the older gcc :smile:

2023-09-19 10:25 UTC, Green-Sky commented
Do you have a test run somewhere?

2023-09-19 10:54 UTC, alonfaraj commented
> Do you have a test run somewhere?

https://github.com/alonfaraj/llama.cpp/actions/runs/6233785774/job/16919688840

2023-09-19 11:46 UTC, Green-Sky approved these changes
lets see if this is more reliable

2023-09-20 12:06 UTC, merged

2023-09-20 16:02 UTC, Cebtenzzre commented
FreeBSD CI isn't working for me:
https://github.com/ggerganov/llama.cpp/actions/runs/6250930942/job/16970883041?pr=3200
```
Error: Waiting for VM to become ready timed out after 120 seconds
```

2023-09-20 16:52 UTC, Green-Sky commented
well, at least it fails fast now (instead of >2h doing nothing)

2023-09-21 08:29 UTC, alonfaraj commented
@Green-Sky 
I was looking around for other solutions because seems like this action doesn't function so well.
I have found https://github.com/vmactions/freebsd-vm which seems to be more stable and didn't notice any reported issues.
I have tested it, ran 10 times in a raw, everything works as expected and looks good.
No warnings etc. like we have now.
The test are [here](https://github.com/alonfaraj/llama.cpp/actions/runs/6257283271).
You can see the 10 attempts on the right upper corner.
Let me know if you think it worth a try before we give up :grin:

2023-09-21 11:14 UTC, Green-Sky commented
hmm I took a look around, and it seems that this runner is still using macos as the "host".
Although it says that you can run qemu on macos, it says:

> The FreeBSD and OpenBSD VMs run on the [xhyve](https://github.com/machyve/xhyve) hypervisor (on a macOS host), while the other platforms run on the [QEMU](https://www.qemu.org/) hypervisor (on a Linux host).

... maybe we should just try a linux host first, just to check.

2023-09-21 20:52 UTC, Cebtenzzre commented
It's working now. What changed? https://github.com/ggerganov/llama.cpp/actions/runs/6266338778/job/17017092230?pr=2268

2023-09-21 23:21 UTC, alonfaraj commented
@Cebtenzzre nothing 😅
It tends to work most of the times by looking at the actions history. 
Seems to be generally unstable.

2023-09-21 23:23 UTC, Green-Sky commented
yea it just flakes sometimes, just rerun it for now.

2023-09-22 16:13 UTC, slaren commented
The difference between a [successful run](https://github.com/ggerganov/llama.cpp/actions/runs/6267949856/job/17022505385) and a [failed run](https://github.com/ggerganov/llama.cpp/actions/runs/6276249352/job/17046309456) seems to be this error:
```
2023-09-22T16:02:27.0894530Z dyld[1311]: Library not loaded: '/usr/local/opt/capstone/lib/libcapstone.4.dylib'
2023-09-22T16:02:27.0996490Z   Referenced from: '/Users/runner/work/_temp/82a0ebe7-06e4-439b-93ce-a0f44424e855/bin/qemu'
2023-09-22T16:02:27.1029200Z   Reason: tried: '/usr/local/opt/capstone/lib/libcapstone.4.dylib' (no such file), '/usr/local/lib/libcapstone.4.dylib' (no such file), '/usr/lib/libcapstone.4.dylib' (no such file), '/usr/local/Cellar/capstone/5.0.1/lib/libcapstone.4.dylib' (no such file), '/usr/local/lib/libcapstone.4.dylib' (no such file), '/usr/lib/libcapstone.4.dylib' (no such file)
```