Address undeclared identifiers by adding conditional compilation
ggml-org/llama.cpp pull request #3631
Opened 2023-10-15 09:50 UTC by danemadsen

This fixes an issue i encountered when compiling my app maid (https://github.com/danemadsen/maid) for android. 
For some reason the __USE_XOPEN2K flag is not defined when compiling for android so POSIX_MADV_WILLNEED and POSIX_MADV_RANDOM throw undefined errors. 

below is the error message i received:
```
flutter build apk --debug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process /home/dane_madsen/Android/Sdk/cmake/3.18.1/bin/ninja with arguments {-C /home/dane_madsen/maid/android/app/.cxx/Debug/221c6fv2/arm64-v8a butler ggml_shared llama}
  ninja: Entering directory `/home/dane_madsen/maid/android/app/.cxx/Debug/221c6fv2/arm64-v8a'
  [1/3] Building CXX object llama.cpp/CMakeFiles/llama.dir/llama.cpp.o
  FAILED: llama.cpp/CMakeFiles/llama.dir/llama.cpp.o 
  /home/dane_madsen/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/dane_madsen/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/dane_madsen/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DGGML_USE_K_QUANTS -DLLAMA_BUILD -DLLAMA_SHARED -D_XOPEN_SOURCE=600 -Dllama_EXPORTS -I/home/dane_madsen/maid/src/llama.cpp/. -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -pthread -std=gnu++11 -MD -MT llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -MF llama.cpp/CMakeFiles/llama.dir/llama.cpp.o.d -o llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -c /home/dane_madsen/maid/src/llama.cpp/llama.cpp
  /home/dane_madsen/maid/src/llama.cpp/llama.cpp:739:17: error: use of undeclared identifier 'posix_madvise'
              if (posix_madvise(addr, std::min(file->size, prefetch), MADV_WILLNEED)) {
                  ^
  /home/dane_madsen/maid/src/llama.cpp/llama.cpp:747:17: error: use of undeclared identifier 'posix_madvise'
              if (posix_madvise(addr, file->size, MADV_RANDOM)) {
                  ^
  2 errors generated.
  ninja: build stopped: subcommand failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Running Gradle task 'assembleDebug'...                              4.6s
Gradle task assembleDebug failed with exit code 1
```

2023-10-15 16:08 UTC, cebtenzzre commented
You're not supposed to check `__USE_XOPEN2K`, you're supposed to use feature test macros to enable it. posix_madvise is normally exposed by setting _POSIX_C_SOURCE to at least `200112L`. Our build scripts effectively do that, AFAIK.

On current bionic libc, all you should have to do is set your target API version to 23, see [here](https://github.com/aosp-mirror/platform_bionic/blob/b4e22199878209822a2f73bfd468df8b3d2208e9/libc/include/sys/mman.h#L223C11-L223C11). I'm not sure why it is missing from your headers.

2023-10-15 16:09 UTC, cebtenzzre requested changes
Checking __USE_XOPEN2K is not correct.

2023-10-17 11:18 UTC, danemadsen commented
It was my NDK version. My bad, thanks for the info

2023-10-17 11:18 UTC, danemadsen commented
Close

2023-10-17 11:18 UTC, closed without merging

2023-10-17 12:19 UTC, danemadsen commented
@cebtenzzre Ok ive done some playing around and i think it must be something on llama.cpp's end.
Ive done like you suggested and tried defining _POSIX_C_SOURCE 200112L, ive checked my SDK_VERSION.

Im not super familiar with NDK development but i cant find any other android implementations of llama.cpp to compare mine against so for now ill just open up an issue and perhaps someone else will have some insight.

2023-10-18 12:16 UTC, gardner commented
Can you try adding `android.externalNativeBuild.cmake` in `android/app/build.gradle` e.g.

```groovy
android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_ARM_NEON=TRUE", "-DANDROID_TOOLCHAIN=clang", "-DANDROID_ABI=arm64-v8a", "-DANDROID_PLATFORM=android-23"
                // abiFilters 'arm64-v8a', 'x86_64'
                cFlags "-march=armv8.4a+dotprod"
            }
        }
```

2023-10-18 12:20 UTC, danemadsen commented
@gardner Haha yeas i saw your fork, ill add it in now and give it a test

2023-10-18 13:16 UTC, cebtenzzre commented
The way I've set the target API with clang in the past is e.g. `-target aarch64-linux-android23`. That should result in \_\_ANDROID\_API\_\_ being set to 23 at compile time.

One way to check the target API is by running clang directly, e.g. in Termux mine defaults to 24:
```console
$ echo '__ANDROID_API__' | clang -E -xc -
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 395 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
24
```

If I add `-target aarch64-linux-android25` to the end of that command, it prints '25' instead.

2023-10-18 13:18 UTC, danemadsen commented
@cebtenzzre Yeah it was on my end. It had to do with cmake compiler flags, I addressed it and its building fine now. Thanks