gguf : track writer state, free unneeded tensors, cleanup
ggml-org/llama.cpp pull request #3871
Opened 2023-10-31 16:09 UTC by cebtenzzre

The idea of checking for incorrect use of GGUFWriter was described here: https://github.com/ggerganov/llama.cpp/pull/3838#discussion_r1375364901

The methods of GGUFWriter are designed to be called in a specific order. This PR makes sure this order is respected, otherwise it will raise an exception. Previously, incorrect use would silently fail in most cases, leaving the user wondering why they got a file with the correct size that fails to load.

Also, when use_temp_file is False, we should remove tensors from the list as soon as we are done with them in order to free the associated memory sooner. This can reduce unnecessary swapping when converting large models with scripts that set that parameter, such as convert-llama-ggml-to-gguf.py.

2023-10-31 18:24 UTC, Galunid commented on gguf-py/gguf/gguf.py
> +        #print("tensors " + str(self.ti_data_count) + " kv " + str(self.kv_data_count))
I think it's best to just remove it. Otherwise looks good :)

2023-11-07 12:18 UTC, Galunid approved these changes
Are we good to merge?

2023-11-07 12:46 UTC, monatis requested changes
Let's also bump the version please

2023-11-07 17:30 UTC, monatis approved these changes

2023-11-07 17:43 UTC, merged