Reduce model loading time
ggml-org/llama.cpp pull request #43
Opened 2023-03-12 10:43 UTC by maekawatoshiki

Hello.

I noticed that the model loader is not using buffered IO, so I added a piece of code for buffering.

I measured the loading time only for llama 7B on my M1 Pro Macbook, but it reduced the time from 1316ms to 749ms.

2023-03-12 10:46 UTC, maekawatoshiki commented on main.cpp
> +    free(f_buf);
`f_buf` will not be free if this function returns earlier, but I think it does not matter since it's a small amount of memory :)

2023-03-12 20:33 UTC, ggerganov requested changes

2023-03-12 20:33 UTC, ggerganov commented on main.cpp
> +    char *f_buf = (char *)malloc(f_buf_size);
Use `std::vector<char>` instead to guarantee memory deallocation on scope exit

2023-03-13 01:39 UTC, maekawatoshiki commented
Thank you for your review. Fixed as mentioned.

2023-03-13 16:33 UTC, ggerganov approved these changes

2023-03-13 16:33 UTC, merged