Generate library with CMake
ggml-org/llama.cpp pull request #430
Opened 2023-03-23 14:14 UTC by nusu-github

BUILD_SHARED_LIBS to allow llama library to be generated.

Resolve #412.

2023-03-23 15:09 UTC, Green-Sky requested changes

2023-03-23 15:09 UTC, Green-Sky commented on CMakeLists.txt
> +    target_compile_definitions(llama PRIVATE LLAMA_SHARED LLAMA_BUILD)
why define `LLAMA_SHARED` `LLAMA_BUILD` ?

2023-03-23 15:19 UTC, Green-Sky commented on CMakeLists.txt
> +    target_compile_definitions(llama PRIVATE LLAMA_SHARED LLAMA_BUILD)
i see :+1:

2023-03-23 15:24 UTC, Green-Sky commented on CMakeLists.txt
> +set_target_properties(utils PROPERTIES POSITION_INDEPENDENT_CODE ON)
i wonder if this can have negative effects, but lets just merge it as is for now.

2023-03-23 19:46 UTC, ggerganov approved these changes

2023-03-23 20:16 UTC, Green-Sky approved these changes

2023-03-23 20:16 UTC, merged

2023-04-02 21:38 UTC, hanss0n commented
I'm still encountering the `/usr/bin/ld: CMakeFiles/test-quantize.dir/test-quantize.c.o: undefined reference to symbol 'roundf@@GLIBC_2.2.5'` error despite this fix 😭