replaced all API facing `int`'s with `int32_t`
ggml-org/llama.cpp pull request #4577
Opened 2023-12-21 21:40 UTC by MarcusDunn

Easy part of #4574

2023-12-22 18:27 UTC, LoganDark requested changes
Almost all of these need to be size_t or ssize_t instead since they represent the sizes of buffers in memory. Basically,

- buffer lengths need to be size_t.
- all indices need to be size_t.
- all counts need to be size_t (n_tokens, n_threads, n_gpu_layers etc)
- tokens themselves should be uint32_t rather than int32_t, because tokens can't be negative.
- functions that return status codes can remain int32_t, as long as they don't smuggle a size in there (then they need to be ssize_t)
- the token encoding/decoding functions that can return a negative size in the case that the buffer is too small, need ssize_t.

This PR definitely doesn't address the majority of the issue in the codebase where int32_t has been chosen for values that really should be size_t or ssize_t instead. int32_t still has a place in some areas, but we surpassed 4GiB of memory decades ago.

disclaimer: I don't represent the llama.cpp project

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +void llama_sample_top_k(struct llama_context * ctx, llama_token_data_array * candidates, int32_t k, size_t min_keep) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +llama_token llama_sample_token_mirostat(struct llama_context * ctx, llama_token_data_array * candidates, float tau, float eta, int32_t m, float * mu) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_n_vocab(const struct llama_model * model) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_n_ctx_train(const struct llama_model * model) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_n_embd(const struct llama_model * model) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_model_meta_val_str(const struct llama_model * model, const char * key, char * buf, size_t buf_size) {
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_model_meta_count(const struct llama_model * model) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_model_meta_key_by_index(const struct llama_model * model, int i, char * buf, size_t buf_size) {
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_model_meta_val_str_by_index(const struct llama_model * model, int32_t i, char * buf, size_t buf_size) {
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_model_desc(const struct llama_model * model, char * buf, size_t buf_size) {
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_get_kv_cache_token_count(const struct llama_context * ctx) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_get_kv_cache_used_cells(const struct llama_context * ctx) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +                     int32_t   n_past) {
size_t (and n_tokens should also be size_t across the whole codebase)

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +                         int32_t   n_past) {
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_tokenize(
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.cpp
> +int32_t llama_token_to_piece(const struct llama_model * model, llama_token token, char * buf, int32_t length) {
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_n_vocab    (const struct llama_model * model);
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_n_ctx_train(const struct llama_model * model);
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_n_embd     (const struct llama_model * model);
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_model_meta_val_str(const struct llama_model * model, const char * key, char * buf, size_t buf_size);
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_model_meta_count(const struct llama_model * model);
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_model_meta_key_by_index(const struct llama_model * model, int32_t i, char * buf, size_t buf_size);
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_model_meta_val_str_by_index(const struct llama_model * model, int32_t i, char * buf, size_t buf_size);
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_model_desc(const struct llama_model * model, char * buf, size_t buf_size);
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_get_kv_cache_token_count(const struct llama_context * ctx);
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_get_kv_cache_used_cells(const struct llama_context * ctx);
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                         int32_t   n_past),
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                         int32_t   n_past),
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_tokenize(
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                         int32_t   text_len,
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                         int32_t   n_max_tokens,
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +    LLAMA_API int32_t llama_token_to_piece(
ssize_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                               int32_t   length);
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                         int32_t   k,
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                         int32_t   m,
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                                int32_t   n_past,
size_t

2023-12-22 18:27 UTC, LoganDark commented on llama.h
> +                                int32_t   n_predict);
size_t

2023-12-22 20:32 UTC, MarcusDunn commented
I think changing to `int`s to `size_t`s as suggested would break things in `examples` and should be done with some care.

This PR is an attempt at some easy wins around making 32 bit `int` assumptions explicit - certainly not sufficient to call #4574 complete.

2023-12-22 20:33 UTC, LoganDark commented
> I think changing to `int`s to `size_t`s as suggested would break things in `examples`

Is ABI compatibility a concern? Because if not we can just update their source code.

2023-12-22 20:41 UTC, MarcusDunn commented
I was more thinking underflow.

2023-12-22 20:43 UTC, slaren commented
There may be some argument between using signed or unsigned types, but I don't see any reason to use `size_t` for any of these. Sized integers are preferred to simplify interoperability. My opinion is that it is better to stick to signed integers unless we really need that last bit, since it often simplifies code logic and may result in faster code due to less strict overflow rules in C/C++.

2023-12-22 20:43 UTC, LoganDark commented
> I was more thinking underflow.

Where exactly would there be underflow in any of the examples? You barely ever need signed computations for any of llama.cpp, the only thing I can think of is the tokenizer functions, which would be ssize_t which is fine.

2023-12-23 02:11 UTC, cebtenzzre commented
> Almost all of these need to be size_t or ssize_t

[YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it).

2023-12-23 02:14 UTC, LoganDark commented
> > Almost all of these need to be size_t or ssize_t
> 
> [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it).

I know that practically, most of these are not going to need the integer precision, but *semantically* they still matter in certain contexts, such as Rust. I have three options:

- Force consumers of my bindings to do the casts to u32/i32 themselves.
- Silently truncate integers and introduce memory unsafety.
- Panic and abort the process if an integer would have been truncated.

None of these are particularly attractive, and while the third one may be most desirable from the downstream dependents' perspective, it's an absolute nightmare to pull off as a library author, because every conversion needs to be manually checked and panicked about.

Just use the proper integer types please.

2024-01-02 14:14 UTC, ggerganov approved these changes

2024-01-02 14:15 UTC, merged