finetune: rename feed-forward tensors (w1/w2/w3)
ggml-org/llama.cpp pull request #4839
Opened 2024-01-09 14:13 UTC by danbev

This commit renames the feed-forward tensors `w1`, `w2` and `w3` to `ffn_gate`, `ffn_down` and `ffn_up` respectively.

The motivation for this change is to make it easier to understand the purpose of the tensors. This also seems to be inline with the names used in the llama_layer struct in llama.cpp.

2024-01-09 15:27 UTC, xaedes requested changes
Looks good to me. 
For consistency, can you do the same for `examples/train-text-from-scratch.cpp` inside this PR?

2024-01-10 04:59 UTC, danbev commented
> For consistency, can you do the same for `examples/train-text-from-scratch.cpp` inside this PR?

Absolutely, I'll take a look at that examples as well :+1:

2024-01-10 10:56 UTC, danbev commented
The [ci failure](https://github.com/ggerganov/llama.cpp/actions/runs/7471618039/job/20332210095?pr=4839#step:5:55) does not look related to this PR as far as I can tell. 
Would someone with the correct permissions be able to re-run the job in question?

2024-01-10 11:20 UTC, ggerganov reviewed
Yeah, sometimes this job fails - restarted it

2024-01-15 18:14 UTC, danbev commented
@xaedes Would you be able to take a look at the changes to train-text-from-scratch.cpp? Thanks

2024-02-13 13:15 UTC, ggerganov approved these changes

2024-02-13 13:15 UTC, merged