Handle cases where git index is not found in .git directory
ggml-org/llama.cpp pull request #5844
Opened 2024-03-03 01:46 UTC by danemadsen

I know Ive tried to merge this in the past and it got denied in favor of handling sub modules explicitly but please reconsider.

This fixes #3902

The issue is not common and in most cases the code to handle sub modules that  has already been added should work but in my case it doesn't work for an unknowable reason.

In the case of maid this error occurs because flutter is trying to build llama.cpp through a simlink to a package added as a submodule which itself includes a submodule (llama.cpp). Somewhere along the line the .git/index gets lost but the .git directory remains so ```if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/../.git")``` succeeds but because .git/index doesn't exist an error occurs.

So my simple fix is to just check that the .git/index exists instead of the .git directory. Which in my mind makes more sense as the crux of what that block of code is doing requires that .git/index exists not that the .git directory exists.

2024-03-03 08:48 UTC, ggerganov commented
> I know Ive tried to merge this in the past and it got denied in favor of handling sub modules explicitly but please reconsider.

I don't see a problem with the proposed change. What was the reason to deny it in the past?

2024-03-03 09:50 UTC, danemadsen commented
> > I know Ive tried to merge this in the past and it got denied in favor of handling sub modules explicitly but please reconsider.
> 
> I don't see a problem with the proposed change. What was the reason to deny it in the past?
> 

I can't find the PR but I think it was denied in favor of handling submodules explicitly like is done in the block of code below my change. But the EXISTS check was never changed.

2024-03-03 09:55 UTC, ggerganov approved these changes

2024-03-03 19:42 UTC, cebtenzzre requested changes
This causes the `if(NOT IS_DIRECTORY "${GIT_DIR}")` check to never be true, meaning submodules and alternate worktrees no longer have commit information. I would prefer if we could fix this without removing functionality.

2024-03-03 19:44 UTC, cebtenzzre commented
Previous discussion here: #5256

2024-03-03 23:50 UTC, danemadsen commented
@cebtenzzre Thanks for the review, Ive adapted the CMake so it shouldn't break that now.

2024-03-04 16:40 UTC, cebtenzzre approved these changes
I suppose this workaround is fine. Ideally we would be able to find the index in all cases, e.g. by using `git rev-parse --git-path index`.

Also, even before this PR it seems like modifying `.git/index` without changing HEAD (e.g. by using `git add`) will cause the build info script to run for every future time you run `make`, until the commit SHA actually changes - not sure if it would be a net good if we always wrote the build info even if it has not changed in `scripts/gen-build-info-cpp.cmake`, as that might cause unnecessary compiler/linker invocations.

2024-03-04 18:26 UTC, merged