Run make to build the project
ggml-org/llama.cpp pull request #6457
Opened 2024-04-03 13:22 UTC by limitedAtonement

Although anyone running `cmake` probably knows to run `make`, we may as well add it for completeness's sake.

2024-04-03 14:10 UTC, phymbert requested changes, later dismissed

2024-04-03 14:10 UTC, phymbert commented on README-sycl.md
> +make
We usually only use `cmake`, I would suggest to change to:

```shell
cmake --build . --config Release -j $(nproc)
```

2024-04-04 18:46 UTC, phymbert reviewed
according to @cebtenzzre comment, forgive my previous comment

2024-04-04 19:45 UTC, cebtenzzre approved these changes

2024-04-07 07:12 UTC, NeoZhangJianyu commented
@limitedAtonement 
Thank your fix!

This issue was created by another PR: https://github.com/ggerganov/llama.cpp/pull/6141

The removed code is :
```
# Or, build all binary
cmake --build . --config Release -v
``` 

If good if you provide both make and cmake here.

2024-04-07 09:46 UTC, limitedAtonement commented
> If good if you provide both make and cmake here.

I wasn't sure how to provide both, so I gave it the old college try. How does that look?

2024-04-07 10:35 UTC, phymbert approved these changes

2024-04-07 11:05 UTC, merged

2024-04-07 15:05 UTC, arthw commented
OK, I will check and update if needed.

Thank you!

2024-04-17 17:52 UTC, abhilash1910 commented
I think this PR needs another look, from usability point of view .

2024-04-17 18:07 UTC, limitedAtonement commented
@abhilash1910 What are your concerns? I used the instructions to build (using `make`, not `cmake --build`).

2024-04-19 01:31 UTC, arthw commented
I test and find the parameter "cmake --build .. xxxx" is wrong in common build env.
I fix it by PR: https://github.com/ggerganov/llama.cpp/pull/6755