Use getopts for example scripts
ggml-org/llama.cpp pull request #664
Opened 2023-03-31 22:38 UTC by siraben

2023-04-01 01:03 UTC, siraben commented
cc @prusnak

2023-04-02 08:28 UTC, ggerganov requested changes

2023-04-02 08:28 UTC, ggerganov commented on examples/chat-13B.sh
> +    m) MODEL="--model $OPTARG";;
Any reason for not doing it like this for consistency:

```suggestion
    m) MODEL="$OPTARG";;
```

2023-04-02 08:28 UTC, ggerganov commented on examples/reason-act.sh
> +./bin/main $MODEL --color \
The example scripts are meant to be run from the source root, so this has to remain `./main`

2023-04-13 12:49 UTC, ggerganov commented
Feel free to reopen if the suggestions are resolved, closing to remove clutter

2023-04-13 12:49 UTC, closed without merging