Feature: Added api for getting/setting the kv_cache
ggml-org/llama.cpp pull request #685
Opened 2023-04-01 15:43 UTC by chrfalch

This PR contains a simple extension to the C-API for getting/setting the kv_cache so that an app can save the state of the kv_cache after providing a prompt and load this next time the app starts to avoid having to evaluate the prompt on startup.

The api provides access methods for retrieving the current memory buffer for the kv_cache and its token number. It also contains a method for setting the kv_cache from a memory buffer and a token count.

I did not start implementing the `--cache-prompt` argument since it is a bit more involved - we need to save some more state like the last_n_tokens and n_past parameter. We'd also need to hash the prompt, check if a prompt file existed etc.

Implements foundation for #64

2023-04-01 15:45 UTC, chrfalch commented
Example app using the new api to load the state is able to answer with previous knowledge from the saved prompt (uses the chat example):

<img width="362" alt="image" src="https://user-images.githubusercontent.com/875252/229299556-bd72508d-13d1-4228-907f-7b198fc52ecc.png">

2023-04-01 16:44 UTC, prusnak requested changes
use `const` where appropriate

2023-04-01 16:44 UTC, prusnak commented on llama.cpp
> +uint8_t* llama_get_kv_cache(struct llama_context * ctx) {
```suggestion
const uint8_t * llama_get_kv_cache(struct llama_context * ctx) {
```

2023-04-01 16:44 UTC, prusnak commented on llama.cpp
> +                     uint8_t * kv_cache,
```suggestion
                     const uint8_t * kv_cache,
```

2023-04-01 16:44 UTC, prusnak commented on llama.h
> +    LLAMA_API uint8_t* llama_get_kv_cache(struct llama_context * ctx);
```suggestion
    LLAMA_API const uint8_t * llama_get_kv_cache(struct llama_context * ctx);
```

2023-04-01 16:44 UTC, prusnak commented on llama.h
> +                         uint8_t * kv_cache,
```suggestion
                         const uint8_t * kv_cache,
```

2023-04-01 16:48 UTC, chrfalch commented
Thanks for the comments, @prusnak - appreciate it.

2023-04-02 10:07 UTC, ggerganov approved these changes
Very good start for solving #64 

Use 4 spaces indentation

2023-04-02 10:19 UTC, prusnak approved these changes

2023-04-02 10:23 UTC, merged