Implemented basic interface for llamacheck and link to weights, adapt…
ggml-org/llama.cpp pull request #6940
Opened 2024-04-27 02:30 UTC by Ferruolo

Provided a simple interface for llamacheck, a finetune of llama that provides spellcheck and grammarcheck functionalities. Although it runs approximately 4 seconds slower than xfspell, I believe that the added functionality is 100% worth it. Linked weights in readme

2024-04-27 04:46 UTC, Galunid requested changes
You are including a binary

2024-04-27 04:46 UTC, Galunid commented on llamacheck
You are including a binary

2024-05-25 11:59 UTC, Galunid commented on Makefile
> +llamacheck: examples/llamacheck/llamacheck.cpp                          ggml.o llama.o $(COMMON_DEPS) $(OBJS)
Please fix whitespaces

2024-05-25 11:59 UTC, Galunid commented on examples/llamacheck/llamacheck.cpp
> +
Could you fix whitespaces in this file? There are multiple instances of double new lines and new lines after comments that shouldn't be there.

2024-05-25 12:45 UTC, mofosyne commented
@Ferruolo is there a reason that the model card is empty in huggingface https://huggingface.co/azferruolo/llamacheck ?

2024-05-31 02:35 UTC, closed without merging