Add BPE pre-tokenization for Command-R.
ggml-org/llama.cpp pull request #7033
Opened 2024-05-02 01:21 UTC by dranger003

I read https://github.com/ggerganov/llama.cpp/pull/6920 and https://github.com/ggerganov/llama.cpp/pull/6920/commits/120cf37d546a82042bd1ad5894e4814a0efa8086 and attempting to add support Command-R support.

Closes https://github.com/ggerganov/llama.cpp/issues/7030.

```
./build/bin/test-tokenizer-0 models/ggml-vocab-command-r.gguf
...
Tests passed
```

2024-05-02 05:20 UTC, ggerganov commented
I tried to run the `convert-hf-to-gguf-update.py` script but it failed because `tokenizer.json` is LFS in that repo. So we need to handle it:

```diff
diff --git a/convert-hf-to-gguf-update.py b/convert-hf-to-gguf-update.py
index f4774003..4ad4d867 100644
--- a/convert-hf-to-gguf-update.py
+++ b/convert-hf-to-gguf-update.py
@@ -95,6 +95,14 @@ for model in models:
     save_path = f"models/tokenizers/{name}/tokenizer.json"
     download_file_with_auth(url, token, save_path)
 
+    # if downloaded file is less than 1KB, we likely need to download an LFS instead
+    if os.path.getsize(save_path) < 1024:
+        # remove the file
+        os.remove(save_path)
+        url = f"{repo}/resolve/main/tokenizer.json"
+        save_path = f"models/tokenizers/{name}/tokenizer.json"
+        download_file_with_auth(url, token, save_path)
+
     if tokt == TOKENIZER_TYPE.SPM:
         url = f"{repo}/resolve/main/tokenizer.model"
         save_path = f"models/tokenizers/{name}/tokenizer.model"
```

2024-05-02 05:27 UTC, drummerv commented
Lets goooooO!

2024-05-02 07:39 UTC, sealad886 requested changes
I've had an a-ha moment, and these look good. I've run it and got the same.

Optional: add in command-r-plus with nearly identical footprint, since the pre-tokenizers are the same (couple ways to make that happen). 

One note: `tokenizer.config` specifies the [Digits pre-tokenizer](https://huggingface.co/docs/tokenizers/en/api/pre-tokenizers#tokenizers.pre_tokenizers.Digits) is used and `individual_digits=True`. There's not a regex pattern in `llama.cpp` explicitly matching individual digits. EVen though the tests pass, would that be a possibilty to add in for completeness sake?

2024-05-02 08:18 UTC, Rotatingxenomorph commented
I get why it's changed, but does it mean the old quants are broken even when using the older versions of llamacpp? I'm not sure I can face downloading and quantizing it myself.

2024-05-02 08:31 UTC, sealad886 commented
> I get why it's changed, but does it mean the old quants are broken even when using the older versions of llamacpp? I'm not sure I can face downloading and quantizing it myself.

My understanding of the overall issue (which admittedly is not as nuanced as others') would suggest that, for the most part, yes you should re-download and re-convert and re-quantize your models. The longer version is that newer models are more likely to use newer pre-tokenizer splits.

Luckily, command-r and command-r-plus appear to be nearly identical to the default pre-tokenizer's splits, so for these models it's __probably__ okay?

2024-05-02 08:35 UTC, Rotatingxenomorph commented
> > I get why it's changed, but does it mean the old quants are broken even when using the older versions of llamacpp? I'm not sure I can face downloading and quantizing it myself.
> 
> My understanding of the overall issue (which admittedly is not as nuanced as others') would suggest that, for the most part, yes you should re-download and re-convert and re-quantize your models. The longer version is that newer models are more likely to use newer pre-tokenizer splits.
> 
> Luckily, command-r and command-r-plus appear to be nearly identical to the default pre-tokenizer's splits, so for these models it's **probably** okay?

I just remembered that the imat quants will be incorrect for the new version of llamacpp. I have a non-imat q6k that I was hoping to use until some kind person makes a new q8 for huggingface ;)

2024-05-02 08:45 UTC, sealad886 commented
> I just remembered that the imat quants will definitely be incorrect for the new version of llamacpp. I have a non-imat q6k that I was hoping to use until some kind person makes a new q8 for huggingface ;)

Yeah exactly...lots of componding issues. I've ended up moving some of these over to Ollama as well, so now I have to untangle what came from me and what I pulled from them. But I wouldn't be surprised if the majority of Ollama models have this same issue and will need to be re-built.

2024-05-02 09:39 UTC, sealad886 approved these changes
Actually, yeah. Let's just approve this to get it in there, and I'll add in command-r-plus separately.

2024-05-02 11:11 UTC, dranger003 commented
This PR works for Command-R version, since they have the same hash.

2024-05-02 11:17 UTC, dranger003 commented
> I tried to run the `convert-hf-to-gguf-update.py` script but it failed because `tokenizer.json` is LFS in that repo. So we need to handle it:
> 
> ```diff
> diff --git a/convert-hf-to-gguf-update.py b/convert-hf-to-gguf-update.py
> index f4774003..4ad4d867 100644
> --- a/convert-hf-to-gguf-update.py
> +++ b/convert-hf-to-gguf-update.py
> @@ -95,6 +95,14 @@ for model in models:
>      save_path = f"models/tokenizers/{name}/tokenizer.json"
>      download_file_with_auth(url, token, save_path)
>  
> +    # if downloaded file is less than 1KB, we likely need to download an LFS instead
> +    if os.path.getsize(save_path) < 1024:
> +        # remove the file
> +        os.remove(save_path)
> +        url = f"{repo}/resolve/main/tokenizer.json"
> +        save_path = f"models/tokenizers/{name}/tokenizer.json"
> +        download_file_with_auth(url, token, save_path)
> +
>      if tokt == TOKENIZER_TYPE.SPM:
>          url = f"{repo}/resolve/main/tokenizer.model"
>          save_path = f"models/tokenizers/{name}/tokenizer.model"
> ```

Thanks, I added this update to the PR.

2024-05-02 20:05 UTC, dranger003 commented
@drummerv I am not getting any errors.

<details>

<summary>convert-hf-to-gguf-update.py</summary>

```
$ python ./convert-hf-to-gguf-update.py hf_token
Downloading llama-spm to models/tokenizers/llama-spm
File models/tokenizers/llama-spm/config.json downloaded successfully
File models/tokenizers/llama-spm/tokenizer.json downloaded successfully
File models/tokenizers/llama-spm/tokenizer.model downloaded successfully
File models/tokenizers/llama-spm/tokenizer_config.json downloaded successfully
Downloading llama-bpe to models/tokenizers/llama-bpe
File models/tokenizers/llama-bpe/config.json downloaded successfully
File models/tokenizers/llama-bpe/tokenizer.json downloaded successfully
File models/tokenizers/llama-bpe/tokenizer_config.json downloaded successfully
Downloading phi-3 to models/tokenizers/phi-3
File models/tokenizers/phi-3/config.json downloaded successfully
File models/tokenizers/phi-3/tokenizer.json downloaded successfully
File models/tokenizers/phi-3/tokenizer.model downloaded successfully
File models/tokenizers/phi-3/tokenizer_config.json downloaded successfully
Downloading deepseek-llm to models/tokenizers/deepseek-llm
File models/tokenizers/deepseek-llm/config.json downloaded successfully
File models/tokenizers/deepseek-llm/tokenizer.json downloaded successfully
File models/tokenizers/deepseek-llm/tokenizer_config.json downloaded successfully
Downloading deepseek-coder to models/tokenizers/deepseek-coder
File models/tokenizers/deepseek-coder/config.json downloaded successfully
File models/tokenizers/deepseek-coder/tokenizer.json downloaded successfully
File models/tokenizers/deepseek-coder/tokenizer_config.json downloaded successfully
Downloading falcon to models/tokenizers/falcon
File models/tokenizers/falcon/config.json downloaded successfully
File models/tokenizers/falcon/tokenizer.json downloaded successfully
File models/tokenizers/falcon/tokenizer_config.json downloaded successfully
Downloading bert-bge to models/tokenizers/bert-bge
File models/tokenizers/bert-bge/config.json downloaded successfully
File models/tokenizers/bert-bge/tokenizer.json downloaded successfully
File models/tokenizers/bert-bge/tokenizer_config.json downloaded successfully
Downloading mpt to models/tokenizers/mpt
File models/tokenizers/mpt/config.json downloaded successfully
File models/tokenizers/mpt/tokenizer.json downloaded successfully
File models/tokenizers/mpt/tokenizer_config.json downloaded successfully
Downloading starcoder to models/tokenizers/starcoder
File models/tokenizers/starcoder/config.json downloaded successfully
File models/tokenizers/starcoder/tokenizer.json downloaded successfully
File models/tokenizers/starcoder/tokenizer_config.json downloaded successfully
Downloading gpt-2 to models/tokenizers/gpt-2
File models/tokenizers/gpt-2/config.json downloaded successfully
File models/tokenizers/gpt-2/tokenizer.json downloaded successfully
File models/tokenizers/gpt-2/tokenizer_config.json downloaded successfully
Downloading command-r to models/tokenizers/command-r
File models/tokenizers/command-r/config.json downloaded successfully
File models/tokenizers/command-r/tokenizer.json downloaded successfully
File models/tokenizers/command-r/tokenizer.json downloaded successfully
File models/tokenizers/command-r/tokenizer_config.json downloaded successfully
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
model: llama-bpe
tokt: 2
repo: https://huggingface.co/meta-llama/Meta-Llama-3-8B
chktok: [128000, 198, 4815, 15073, 66597, 8004, 1602, 2355, 79772, 11187, 9468, 248, 222, 320, 8416, 8, 27623, 114, 102470, 9468, 234, 104, 31643, 320, 36773, 100166, 98634, 8, 26602, 227, 11410, 99, 247, 9468, 99, 247, 220, 18, 220, 1644, 220, 8765, 220, 8765, 18, 220, 8765, 1644, 220, 8765, 8765, 220, 8765, 8765, 18, 220, 8765, 8765, 1644, 220, 18, 13, 18, 220, 18, 497, 18, 220, 18, 1131, 18, 220, 21549, 222, 98629, 241, 45358, 233, 21549, 237, 45358, 224, 21549, 244, 21549, 115, 21549, 253, 45358, 223, 21549, 253, 21549, 95, 98629, 227, 76460, 223, 949, 37046, 101067, 19000, 23182, 102301, 9263, 18136, 16, 36827, 21909, 56560, 54337, 19175, 102118, 13373, 64571, 34694, 3114, 112203, 80112, 3436, 106451, 14196, 14196, 74694, 3089, 3089, 29249, 17523, 3001, 27708, 7801, 358, 3077, 1027, 364, 83, 820, 568, 596, 1070, 11, 364, 793, 499, 2771, 30, 364, 44, 539, 2771, 358, 3358, 1304, 433, 11, 364, 35, 499, 1093, 1063, 15600, 30, 1226, 6, 43712, 264, 64966, 43]
chkhsh: 0ef9807a4087ebef797fc749390439009c3b9eda9ad1a097abbe738f486c01e5
pre_tokenizer: {
    "type": "Sequence",
    "pretokenizers": [
        {
            "type": "Split",
            "pattern": {
                "Regex": "(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+"
            },
            "behavior": "Isolated",
            "invert": false
        },
        {
            "type": "ByteLevel",
            "add_prefix_space": false,
            "trim_offsets": true,
            "use_regex": false
        }
    ]
}


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
model: deepseek-llm
tokt: 2
repo: https://huggingface.co/deepseek-ai/deepseek-llm-7b-base
chktok: [100000, 185, 207, 185, 185, 207, 185, 185, 185, 207, 11969, 486, 22504, 185, 243, 185, 300, 185, 251, 185, 663, 185, 10044, 95300, 334, 8754, 8, 33701, 114, 350, 222, 10044, 221, 104, 46713, 334, 34732, 996, 24250, 262, 80923, 8, 207, 37103, 214, 12356, 99, 234, 10044, 99, 234, 207, 18, 207, 18, 18, 207, 18, 18, 18, 207, 18, 18, 18, 18, 207, 18, 18, 18, 18, 18, 207, 18, 18, 18, 18, 18, 18, 207, 18, 18, 18, 18, 18, 18, 18, 207, 18, 18, 18, 18, 18, 18, 18, 18, 207, 18, 13, 18, 207, 18, 526, 18, 207, 18, 1204, 18, 207, 71374, 209, 71374, 114, 71374, 228, 155, 240, 220, 71374, 224, 155, 240, 211, 71374, 231, 71374, 115, 71374, 240, 155, 240, 210, 71374, 240, 71374, 95, 71374, 114, 71374, 214, 71899, 210, 3025, 19017, 612, 9407, 2681, 16, 18, 16, 19, 16, 20, 16, 1398, 68940, 239, 78827, 55170, 76659, 620, 91754, 31116, 36804, 4885, 4885, 10897, 4390, 4390, 41047, 15278, 3033, 14986, 5675, 304, 6, 313, 803, 655, 33326, 362, 6, 82, 745, 11, 655, 1374, 340, 2049, 30, 655, 44, 441, 2049, 304, 6, 647, 1099, 359, 11, 655, 35, 340, 837, 742, 10842, 30, 1003, 6, 10699, 245, 6, 75, 43]
chkhsh: 049ecf7629871e3041641907f3de7c733e4dbfdc736f57d882ba0b0845599754
pre_tokenizer: {
    "type": "Sequence",
    "pretokenizers": [
        {
            "type": "Split",
            "pattern": {
                "Regex": "[\r\n]"
            },
            "behavior": "Isolated",
            "invert": false
        },
        {
            "type": "Split",
            "pattern": {
                "Regex": "\\s?[A-Za-z\u00b5\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u01ba\u01bc-\u01bf\u01c4-\u0293\u0295-\u02af\u0370-\u0373\u0376\u0377\u037b-\u037d\u037f\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03f5\u03f7-\u0481\u048a-\u052f\u0531-\u0556\u10a0-\u10c5\u13a0-\u13f5\u13f8-\u13fd\u1c90-\u1cba\u1cbd-\u1cbf\u1d00-\u1d2b\u1d6b-\u1d77\u1d79-\u1d9a\u1e00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2102\u2107\u210a-\u2113\u2115\u2119-\u211d\u2124\u2126\u2128\u212a-\u212d\u212f-\u2134\u2139\u213c-\u213f\u2145-\u2149\u214e\u2183\u2184\u2c00-\u2c7b\u2c7e-\u2ce4\u2ceb-\u2cee\u2cf2\u2cf3\ua640-\ua66d\ua680-\ua69b\ua722-\ua76f\ua771-\ua787\ua78b-\ua78e\uab70-\uabbf\ufb00-\ufb06\ufb13-\ufb17\uff21-\uff3a\uff41-\uff5a\ud801\udc00-\ud801\udc4f\ud801\udcb0-\ud801\udcd3\ud801\udcd8-\ud801\udcfb\ud803\udc80-\ud803\udcb2\ud803\udcc0-\ud803\udcf2\ud806\udca0-\ud806\udcdf\ud83a\udd00-\ud83a\udd43]+"
            },
            "behavior": "Isolated",
            "invert": false
        },
        {
            "type": [...]

2024-05-03 19:51 UTC, dranger003 commented
Superseded by PR https://github.com/ggerganov/llama.cpp/pull/7063.

2024-05-03 19:51 UTC, closed without merging