convert-hf-to-gguf-update.py: Added Ukrainian tokens into string
ggml-org/llama.cpp pull request #7888
Opened 2024-06-11 20:40 UTC by AragonerUA

- Self Reported Review Complexity:
    - [X] Review Complexity : Low
    - [ ] Review Complexity : Medium
    - [ ] Review Complexity : High
- [X] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)

2024-06-12 23:59 UTC, treeleaves30760 approved these changes

2024-06-23 14:39 UTC, Galunid requested changes
This will break `convert-hf-to-gguf.py`. You need to have the same `chktxt` in both scripts

2024-06-23 15:52 UTC, AragonerUA commented
> This will break `convert-hf-to-gguf.py`. You need to have the same `chktxt` in both scripts

Done by changing `chktxt` in `conver-hf-to-gguf.py`. I've proposed changes via new pull request.

2024-06-24 09:28 UTC, Galunid commented
It would be best to keep both changes in one PR, since on their own they break the code.

2024-07-11 10:14 UTC, closed without merging