vulkan: detect multiple devices by deviceUUID instead of deviceID
ggml-org/llama.cpp pull request #8022
Opened 2024-06-20 00:48 UTC by Adriankhl

Fixes https://github.com/ggerganov/llama.cpp/issues/7997

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [X] Low
  - [ ] Medium
  - [ ] High

2024-06-20 07:20 UTC, 0cc4m requested changes
I tested it and it works. I just have a few small comments about the code style, once you addressed those this can be merged.

2024-06-20 07:20 UTC, 0cc4m commented on ggml-vulkan.cpp
> +            vk::PhysicalDeviceProperties new_props_1 = devices[i].getProperties();
This isn't needed, you can get the PhysicalDeviceProperties from `new_props_2.properties`. Then you also don't need to call it "new_props_2`, just `new_props`

2024-06-20 07:20 UTC, 0cc4m commented on ggml-vulkan.cpp
> +                        vk::PhysicalDeviceProperties2 old_props_2;
No need for the 2, `old_props`

2024-06-20 07:20 UTC, 0cc4m commented on ggml-vulkan.cpp
> +                    vk::PhysicalDeviceProperties2 old_props_2;
See above

2024-06-20 11:37 UTC, Adriankhl commented
@0cc4m ok done

2024-06-20 20:07 UTC, 0cc4m requested changes
I'm not sure how I missed that, it seemed to be working before. You need to actually fill the old_id.

2024-06-20 20:07 UTC, 0cc4m commented on ggml-vulkan.cpp
> +                        vk::PhysicalDeviceIDProperties old_id;
```suggestion
                        vk::PhysicalDeviceIDProperties old_id;
                        old_props.pNext = &old_id;
```

2024-06-21 08:27 UTC, 0cc4m approved these changes
Thank you, now it's working as intended!

2024-06-21 08:28 UTC, merged