[SYCL] Add `TIMESTEP_EMBEDDING` OP
ggml-org/llama.cpp pull request #8707
Opened 2024-07-26 08:40 UTC by zhentaoyu

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

Add SYCL `TIMESTEP_EMBEDDING` operator by following the related CUDA kernel. 
temporary solution to support SYCL backend for stablediffusion.cpp https://github.com/leejet/stable-diffusion.cpp/issues/308

2024-07-26 08:59 UTC, airMeng approved these changes

2024-07-29 01:18 UTC, airMeng commented
https://github.com/ggerganov/ggml/pull/900 please add t5 layernorm using this PR too

2024-07-30 01:48 UTC, zhentaoyu commented
> [ggerganov/ggml#900](https://github.com/ggerganov/ggml/pull/900) please add t5 layernorm using this PR too

Will add them in another PR. Thanks.

2024-07-30 01:55 UTC, zhentaoyu commented
rebased. @luoyu-intel please take a look. Thanks.

2024-07-30 02:00 UTC, luoyu-intel requested changes

2024-07-30 05:50 UTC, zhentaoyu commented on ggml/src/ggml-sycl/tsembd.cpp
> +    int half_ceil = (dim + 1) / 2;
thanks. fixed

2024-07-30 06:11 UTC, luoyu-intel approved these changes

2024-07-30 06:56 UTC, merged