cann: merge get row operations of float type
ggml-org/llama.cpp pull request #9090
Opened 2024-08-19 07:27 UTC by kylo5aby

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [X] Low
  - [ ] Medium
  - [ ] High
@hipudding  can you please take a look?

2024-08-19 09:24 UTC, hipudding requested changes

2024-08-19 09:24 UTC, hipudding commented on ggml/src/ggml-cann/kernels/get_row_float.cpp
> +    GET_ROW_FLOAT<half> op;
error: calling a private constructor of class 'GET_ROW_FLOAT<half>

2024-08-19 09:24 UTC, hipudding commented on ggml/src/ggml-cann/kernels/get_row_float.cpp
> +    op.calculate();
'calculate' is a private member of 'GET_ROW_FLOAT<half>'

2024-08-19 09:24 UTC, hipudding commented on ggml/src/ggml-cann/kernels/get_row_float.cpp
> +    GET_ROW_FLOAT<float> op;
error: calling a private constructor of class 'GET_ROW_FLOAT<float>'

2024-08-19 09:25 UTC, hipudding commented
I can't build this PR in my local environment. 
Could you please tell me your NPU type, OS, CANN version and build command?

2024-09-02 04:49 UTC, kylo5aby commented
@hipudding can you please take a look?

2024-09-03 07:34 UTC, hipudding commented
@kylo5aby Yes, course. BTW, did you run llama.cpp with 310 NPU? I thought it even can't pass build. How's the performance.

2024-09-04 01:19 UTC, hipudding commented
@kylo5aby Can you also merge duplicate file for get_row_q4 and get_row_q8, Thanks.

2024-09-04 01:42 UTC, hipudding commented on ggml/src/ggml-cann/kernels/get_row_float.cpp
> +        if constexpr (std::is_same<ROW_TYPE, half>::value) {
This part of the code is redundant. Regardless of whether ROW_TYPE is half or float, the execution logic is the same, so there is no need to make a distinction.

In addition, can you write memory alignment as an inline function? This way the code looks cleaner

2024-09-10 01:46 UTC, kylo5aby commented
> @kylo5aby Yes, of course. BTW, did you run llama.cpp with 310 NPU? I thought it even can't pass build. How's the performance.
> 
> Is it a 310 NPU or 310P NPU.

Actually I have just build it without run on llama.cpp

2024-09-10 01:46 UTC, kylo5aby commented
> @kylo5aby Can you also merge duplicate file for get_row_q4 and get_row_q8, Thanks.

I'll do it

2024-09-10 06:25 UTC, hipudding commented
> > @kylo5aby Yes, of course. BTW, did you run llama.cpp with 310 NPU? I thought it even can't pass build. How's the performance.
> > Is it a 310 NPU or 310P NPU.
> 
> Actually I have just build it without run on llama.cpp

Can you run it on 310P, I'd like to know the performance on this NPU.

2025-04-09 06:05 UTC, hipudding commented
AscendC kernels has been removed, this PR will closed.

2025-04-09 06:05 UTC, closed without merging