Use VLAs when possible
ggml-org/llama.cpp pull request #922
Opened 2023-04-12 18:50 UTC by Rhialto

Regarding https://github.com/ggerganov/llama.cpp/pull/918#issuecomment-1505633286 , and 
https://github.com/ggerganov/llama.cpp/pull/918#issuecomment-1505599905 and #881, here is another way: use VLAs instead of alloca, when possible.

It uses `__STDC_NO_VLA__` to detect if VLAs are unavailable, in which case it falls back to alloca. In that case the program is still not a strictly conforming C program, and the `-std=c11` argument to `gcc` may evoke warnings, but on the other hand, gcc is quite likely to support VLAs in practice.

2023-04-17 18:21 UTC, Rhialto commented on ggml.c
> +     struct ggml_compute_state workers[n_threads];
Oh it seems I forgot to actually push that branch... well now I have also rebased it on master.

2023-04-17 19:55 UTC, sw approved these changes

2023-04-17 20:06 UTC, ggerganov requested changes
VLAs can still involve heap allocation.

Sorry to make a big deal of this, but [ggml](https://github.com/ggerganov/ggml) features state "Zero memory allocations during runtime".

Let's add `GGML_NO_ALLOCA` macro to the Makefile + CMake and if set - fallback to VLAs.

2023-04-17 20:55 UTC, Rhialto commented
Well, like I mentioned before: another option is to stop claiming the program is Standard C (as expressed by `-std=c11` and `-std=c++11`) and instead admit it isn't: `-std=gnu11` and `-std=gnu++11`. Whichever is more important to you.

2023-09-15 13:12 UTC, alitariq4589 commented
Can one of the admins verify this patch?

2024-02-19 14:38 UTC, closed without merging