feat: Implements retrying logic for downloading models using --model-url flag
ggml-org/llama.cpp pull request #9255
Opened 2024-08-30 21:11 UTC by farbodbj

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ x ] Low
  - [ ] Medium
  - [ ] High

This PR implements the improvement requested at #6288, the approach is simple and uses a while loop for retrying with exponential backoff.
I found two calls to `curl_easy_perform` which is the [function responsible for transferring the data](https://curl.se/libcurl/c/curl_easy_perform.html), and on the call sites, I added the while loop for retrying on the condition of failing.
For now, the retry count is fixed as a local variable inside the function, but passing the retry count as a CLI argument can further improve this feature.
I compiled the project after the changes with `make LLAMA_CURL=1` and tested it both with and without internet connection and it worked okay.
It's my first time working with `curl` API in cpp so any suggestion for improvement is appreciated.

2024-08-31 08:44 UTC, ngxson requested changes

2024-08-31 08:44 UTC, ngxson commented on common/common.cpp
> +        int retry_delay = 2;
Value of `head_request_attempts` and `retry_delay` are fixed, you can extract it to a `#define`, for example:

```c
#define CURL_MAX_RETRY 3
#define CURL_RETRY_DELAY_SECONDS 2
```


```suggestion
        int remaining_request_attempts = CURL_MAX_RETRY;
```

2024-08-31 08:44 UTC, ngxson commented on common/common.cpp
> +                int exponential_backoff_delay = std::pow(retry_delay, (head_request_attempts - remaining_request_attempts)) * 1000;
Then use the defined:

```suggestion
                int exponential_backoff_delay = std::pow(CURL_RETRY_DELAY_SECONDS, (CURL_MAX_RETRY - remaining_request_attempts)) * 1000;
```

2024-08-31 13:47 UTC, farbodbj commented
@ngxson 
I applied your comments. wasn't sure where I had to put my `#define`s so I put them right above the function using them.

2024-09-01 06:12 UTC, farbodbj commented
I would also appreciate if someone can help me to fix the `editorconfig-checker` CI job, I couldn't figure out how to run the job locally to fix formatting and white space problems

2024-09-05 00:08 UTC, slaren approved these changes
I would suggest extracting the retry logic to a function rather than duplicating the code.

2024-09-05 00:08 UTC, slaren commented on common/common.cpp
> +        while (remaining_request_attempts > 0){
```suggestion
        while (remaining_request_attempts > 0) {
```

2024-09-05 00:08 UTC, slaren commented on common/common.cpp
> +        while (remaining_attempts > 0){
```suggestion
        while (remaining_attempts > 0) {
```

2024-09-07 12:49 UTC, slaren approved these changes

2024-09-10 15:14 UTC, slaren commented
@ngxson Please update your review.

2024-09-10 20:48 UTC, ngxson approved these changes
Thanks. I'll merge when CI passes

2024-09-11 09:22 UTC, merged