Fix for quantize fail on init due to undefined static initialization of complex objects
ggml-org/llama.cpp pull request #927
Opened 2023-04-12 23:37 UTC by arikpoz

Addresses issue #920 

Replaced static initialization of complex objects with a initialization on first use. This prevents an undefined behavior on program run, for example, crash in Release build, works in Debug build

2023-04-13 13:10 UTC, jayliang701 commented
@arikpoz this MR still can not fix the issue.

![image](https://user-images.githubusercontent.com/8044568/231768827-cf4f2872-469d-482c-8e1c-2643cce3199a.png)

2023-04-13 14:35 UTC, arikpoz commented
@jayliang701 , do you get the same behavior if you compile in Debug vs. Release? 
If it works in Debug and fails on Release, try to compile in Release with Debug symbols, and get a more accurate location of the exception

2023-04-14 21:20 UTC, arikpoz commented
@ggerganov , after fixed AVX flag mentioned in PR #809 , the original crash on static initialization I had with quantize disappeared. That said, I believe this is random behavior of the compiler and we should keep the changes suggested in this PR, since when you have static initialization of complex objects that uses other modules (std::) there is no guaranteed order for running the static initializers across the different modules, so the behavior is undefined. See https://en.cppreference.com/w/cpp/language/siof for reference

2023-04-15 11:00 UTC, ggerganov requested changes
I really don't think these static maps can ever cause initialization order problems as they are used only the current translation unit.

But anyway, it does not hurt to change it as suggested.
Just make the functions static and return const references

2023-04-15 17:52 UTC, arikpoz commented
Updated code as requested

2023-04-17 14:38 UTC, arikpoz commented
Let me know if something is missing to merge this

2023-04-17 14:41 UTC, ggerganov approved these changes

2023-04-17 14:41 UTC, merged