[SYCL] Fix build on Windows when ccache enabled (#9954)
ggml-org/llama.cpp pull request #9976
Opened 2024-10-21 08:54 UTC by shou692199

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

2024-10-23 00:43 UTC, NeoZhangJianyu commented
@shou692199
How much time be reduced by CCache in your case?

2024-10-23 04:10 UTC, shou692199 commented
> @shou692199 How much time be reduced by CCache in your case?

About 5 sec on my 16C32T computer.

2024-11-09 11:33 UTC, ggerganov approved these changes

2025-01-02 16:55 UTC, Rbiessy requested changes
I'm not sure about this change. This seems to reduce the cache hit on Unix. Just compiling `llama-bench` on the main branch I get:
```
$ ccache -s
Cacheable calls:   192 /  288 (66.67%)
  Hits:            144 /  192 (75.00%)
    Direct:        144 /  144 (100.0%)
    Preprocessed:    0 /  144 ( 0.00%)
  Misses:           48 /  192 (25.00%)
Uncacheable calls:  96 /  288 (33.33%)
Local storage:
  Cache size (GB): 0.0 / 30.0 ( 0.01%)
  Hits:            144 /  192 (75.00%)
  Misses:           48 /  192 (25.00%)
```
but with this patch this falls to 50%:
```
$ ccache -s
Cacheable calls:    96 /  144 (66.67%)
  Hits:             48 /   96 (50.00%)
    Direct:         48 /   48 (100.0%)
    Preprocessed:    0 /   48 ( 0.00%)
  Misses:           48 /   96 (50.00%)
Uncacheable calls:  48 /  144 (33.33%)
Local storage:
  Cache size (GB): 0.0 / 30.0 ( 0.01%)
  Hits:             48 /   96 (50.00%)
  Misses:           48 /   96 (50.00%)
```
It is curious that this compiler_type is not needed on Unix. Maybe it is safer to only set it for Windows?

2025-01-06 09:20 UTC, Rbiessy approved these changes
Thanks, I'm not sure what is the impact of setting `icl` as the compiler type but it should be fine. I'm happy if @NeoZhangJianyu also is.

2025-03-20 15:07 UTC, Rbiessy commented
I fixed some conflict, I'm planning to merge it tomorrow.

2025-03-21 06:58 UTC, NeoZhangJianyu approved these changes

2025-03-21 06:58 UTC, merged